/*
 * Porest 카테고리 아이콘 세트 — 카테고리 · 저축 목표에 붙이는 아이콘을 고르는 Icon Picker 의 범위(2026-10-09).
 * 원본은 specs/components/category-icons.yaml 이다. 아래 @generated 구역(아이콘 import · DEFAULT_CATEGORY_ICON · CATEGORY_ICON_GROUPS ·
 * CATEGORY_ICONS · CATEGORY_ICON_COMPONENTS)은 scripts/gen-category-icons.mjs 가 그 YAML 에서 만든다 — 손으로 고치지 않는다.
 * 세트를 바꾸려면 YAML 을 고치고 `npm run gen:category-icons` 로 다시 만든다. `npm run verify`(check:category-icons)가 표와 YAML 이
 * 어긋나거나 lucide-react(Desk 웹의 판 — 1.28.0)에 없는 아이콘이 있으면 멈춘다. 앱도 같은 YAML 에서 만든다.
 *
 * lucide 전체(2,007)를 열지 않고 카테고리에 쓸 만한 것만 묶음으로 둔다(사용자 결정 15A). 이름은 한국어 하나 — 칸의 이름(보조 기술 ·
 * 툴팁)과 트리거의 값 글이다. 영어 lucide 이름(id)은 저장 값일 뿐 화면에 내지 않는다.
 *
 *   findCategoryIcon(id)       저장 값(lucide 이름) → 세트의 한 줄. id 또는 lucideAliases(옛 이름 — 서버 시드의 home)로 찾는다.
 *                              세트 밖 · 빈 값이면 null — 빈 값(null · "")은 DEFAULT_CATEGORY_ICON(태그)으로 그리고, 세트 밖 저장 값은
 *                              지우지 않고 그대로 그린다(lucide-react/dynamic 의 DynamicIcon)
 *   searchCategoryIcons(query) 찾는 말 → 걸린 아이콘(세트 차례 그대로). 찾는 말과 name · aliases · id 를 소문자로 바꾸고 공백을 모두 뺀 뒤
 *                              부분 일치다("커피" → 커피 · 원두, "월세" → 집, "coffee" → 커피). 빈 찾는 말이면 세트 전체
 */

// @generated:start (category-icons.yaml — scripts/gen-category-icons.mjs 가 만든다, 손으로 고치지 않는다)
import type { LucideIcon } from "lucide-react";
import {
  Activity as ActivityIcon,
  Apple as AppleIcon,
  ArrowLeftRight as ArrowLeftRightIcon,
  Baby as BabyIcon,
  Backpack as BackpackIcon,
  Banknote as BanknoteIcon,
  Bean as BeanIcon,
  Bed as BedIcon,
  Beef as BeefIcon,
  Beer as BeerIcon,
  Bike as BikeIcon,
  Book as BookIcon,
  BookOpen as BookOpenIcon,
  Bookmark as BookmarkIcon,
  Box as BoxIcon,
  Briefcase as BriefcaseIcon,
  Building as BuildingIcon,
  Bus as BusIcon,
  Cake as CakeIcon,
  CakeSlice as CakeSliceIcon,
  Calculator as CalculatorIcon,
  Camera as CameraIcon,
  Candy as CandyIcon,
  Car as CarIcon,
  CarTaxiFront as CarTaxiFrontIcon,
  Carrot as CarrotIcon,
  Cat as CatIcon,
  ChartLine as ChartLineIcon,
  ChefHat as ChefHatIcon,
  Church as ChurchIcon,
  CircleParking as CircleParkingIcon,
  Clapperboard as ClapperboardIcon,
  Coffee as CoffeeIcon,
  Coins as CoinsIcon,
  Cookie as CookieIcon,
  CreditCard as CreditCardIcon,
  Croissant as CroissantIcon,
  CupSoda as CupSodaIcon,
  Dice5 as Dice5Icon,
  Dog as DogIcon,
  Drama as DramaIcon,
  Droplet as DropletIcon,
  Drumstick as DrumstickIcon,
  Dumbbell as DumbbellIcon,
  EggFried as EggFriedIcon,
  Ellipsis as EllipsisIcon,
  Eye as EyeIcon,
  Film as FilmIcon,
  Fish as FishIcon,
  Flame as FlameIcon,
  Flower as FlowerIcon,
  Folder as FolderIcon,
  Fuel as FuelIcon,
  Gamepad2 as Gamepad2Icon,
  Gem as GemIcon,
  Gift as GiftIcon,
  GlassWater as GlassWaterIcon,
  Glasses as GlassesIcon,
  Globe as GlobeIcon,
  GraduationCap as GraduationCapIcon,
  Guitar as GuitarIcon,
  Hamburger as HamburgerIcon,
  HandCoins as HandCoinsIcon,
  HandHeart as HandHeartIcon,
  Headphones as HeadphonesIcon,
  Heart as HeartIcon,
  HeartHandshake as HeartHandshakeIcon,
  HeartPulse as HeartPulseIcon,
  Hospital as HospitalIcon,
  Hotel as HotelIcon,
  House as HouseIcon,
  IceCreamCone as IceCreamConeIcon,
  KeyRound as KeyRoundIcon,
  Lamp as LampIcon,
  Landmark as LandmarkIcon,
  Languages as LanguagesIcon,
  Laptop as LaptopIcon,
  Library as LibraryIcon,
  Luggage as LuggageIcon,
  Mail as MailIcon,
  MailOpen as MailOpenIcon,
  Map as MapIcon,
  MapPin as MapPinIcon,
  Martini as MartiniIcon,
  Milk as MilkIcon,
  Mountain as MountainIcon,
  Music as MusicIcon,
  NotebookPen as NotebookPenIcon,
  Package as PackageIcon,
  PaintRoller as PaintRollerIcon,
  Palette as PaletteIcon,
  PartyPopper as PartyPopperIcon,
  PawPrint as PawPrintIcon,
  Pencil as PencilIcon,
  Percent as PercentIcon,
  PiggyBank as PiggyBankIcon,
  Pill as PillIcon,
  Pizza as PizzaIcon,
  Plane as PlaneIcon,
  Popcorn as PopcornIcon,
  Puzzle as PuzzleIcon,
  Receipt as ReceiptIcon,
  Repeat as RepeatIcon,
  Route as RouteIcon,
  Salad as SaladIcon,
  Sandwich as SandwichIcon,
  School as SchoolIcon,
  Scissors as ScissorsIcon,
  ShieldCheck as ShieldCheckIcon,
  Ship as ShipIcon,
  Shirt as ShirtIcon,
  ShoppingBag as ShoppingBagIcon,
  ShoppingBasket as ShoppingBasketIcon,
  ShoppingCart as ShoppingCartIcon,
  Smartphone as SmartphoneIcon,
  Smile as SmileIcon,
  Sofa as SofaIcon,
  Soup as SoupIcon,
  Sparkles as SparklesIcon,
  SprayCan as SprayCanIcon,
  Sprout as SproutIcon,
  Star as StarIcon,
  Stethoscope as StethoscopeIcon,
  Store as StoreIcon,
  Syringe as SyringeIcon,
  Tag as TagIcon,
  Tent as TentIcon,
  Ticket as TicketIcon,
  TrainFront as TrainFrontIcon,
  TramFront as TramFrontIcon,
  Trash2 as Trash2Icon,
  TreePalm as TreePalmIcon,
  TrendingUp as TrendingUpIcon,
  Trophy as TrophyIcon,
  Tv as TvIcon,
  Umbrella as UmbrellaIcon,
  Users as UsersIcon,
  Utensils as UtensilsIcon,
  UtensilsCrossed as UtensilsCrossedIcon,
  Wallet as WalletIcon,
  WashingMachine as WashingMachineIcon,
  Watch as WatchIcon,
  WavesHorizontal as WavesHorizontalIcon,
  Wheat as WheatIcon,
  Wifi as WifiIcon,
  Wine as WineIcon,
  Wrench as WrenchIcon,
  Zap as ZapIcon,
} from "lucide-react";

/** 기본 아이콘 — 새 항목 · 아이콘이 없는 항목(null · "") */
export const DEFAULT_CATEGORY_ICON = "tag";

/** 묶음 차례 — 격자는 이 차례로 묶음을 둔다 */
export const CATEGORY_ICON_GROUPS = ["식비", "카페", "교통", "주거", "생활", "쇼핑", "건강", "금융", "여가", "여행", "교육", "경조사", "기타"] as const;

/** 세트 — 묶음 안은 이 차례, 찾기 결과도 이 차례다 */
export const CATEGORY_ICONS: readonly CategoryIcon[] = [
  // ── 식비 ──────────────────────────────────────────────
  { id: "utensils", group: "식비", name: "식사", aliases: ["밥", "식비", "식당", "외식", "점심", "저녁", "끼니"] },
  { id: "utensils-crossed", group: "식비", name: "외식", aliases: ["식당", "레스토랑", "맛집"] },
  { id: "chef-hat", group: "식비", name: "요리", aliases: ["집밥", "셰프", "주방"] },
  { id: "soup", group: "식비", name: "국 · 찌개", aliases: ["한식", "탕", "국밥", "찌개"] },
  { id: "salad", group: "식비", name: "샐러드", aliases: ["채소", "다이어트", "건강식"] },
  { id: "sandwich", group: "식비", name: "샌드위치", aliases: ["빵", "간편식", "브런치"] },
  { id: "pizza", group: "식비", name: "피자", aliases: ["배달", "야식"] },
  { id: "hamburger", group: "식비", name: "햄버거", aliases: ["버거", "패스트푸드"] },
  { id: "drumstick", group: "식비", name: "치킨", aliases: ["닭", "통닭", "야식", "배달"] },
  { id: "beef", group: "식비", name: "고기", aliases: ["정육", "소고기", "돼지고기", "고깃집"] },
  { id: "fish", group: "식비", name: "생선", aliases: ["수산", "회", "해산물"] },
  { id: "egg-fried", group: "식비", name: "달걀", aliases: ["계란", "아침"] },
  { id: "croissant", group: "식비", name: "빵", aliases: ["베이커리", "제과", "빵집"] },
  { id: "cake-slice", group: "식비", name: "케이크", aliases: ["디저트", "생일"] },
  { id: "ice-cream-cone", group: "식비", name: "아이스크림", aliases: ["디저트", "빙과"] },
  { id: "cookie", group: "식비", name: "과자", aliases: ["간식", "쿠키"] },
  { id: "candy", group: "식비", name: "사탕", aliases: ["간식", "젤리", "초콜릿"] },
  { id: "apple", group: "식비", name: "과일", aliases: ["사과", "청과"] },
  { id: "carrot", group: "식비", name: "채소", aliases: ["당근", "야채", "농산물"] },
  { id: "popcorn", group: "식비", name: "팝콘", aliases: ["간식", "영화관"] },
  { id: "milk", group: "식비", name: "우유", aliases: ["유제품"] },
  { id: "wheat", group: "식비", name: "쌀 · 곡물", aliases: ["쌀", "밀", "잡곡"] },
  { id: "shopping-basket", group: "식비", name: "장보기", aliases: ["마트", "시장", "식료품"] },
  // ── 카페 ──────────────────────────────────────────────
  { id: "coffee", group: "카페", name: "커피", aliases: ["카페", "아메리카노", "라떼", "음료", "스타벅스"] },
  { id: "cup-soda", group: "카페", name: "음료", aliases: ["탄산", "주스", "콜라", "사이다"] },
  { id: "glass-water", group: "카페", name: "물", aliases: ["생수", "정수기"] },
  { id: "beer", group: "카페", name: "맥주", aliases: ["술", "호프", "주류"] },
  { id: "wine", group: "카페", name: "와인", aliases: ["술", "주류"] },
  { id: "martini", group: "카페", name: "칵테일", aliases: ["술", "바", "주류"] },
  { id: "bean", group: "카페", name: "원두", aliases: ["커피콩", "콩"] },
  // ── 교통 ──────────────────────────────────────────────
  { id: "bus", group: "교통", name: "버스", aliases: ["대중교통", "교통", "교통비", "시내버스"] },
  { id: "train-front", group: "교통", name: "지하철", aliases: ["전철", "기차", "대중교통", "교통비"] },
  { id: "tram-front", group: "교통", name: "트램", aliases: ["경전철", "노면전차"] },
  { id: "car", group: "교통", name: "자동차", aliases: ["차", "자가용", "운전"] },
  { id: "car-taxi-front", group: "교통", name: "택시", aliases: ["카카오택시", "콜택시"] },
  { id: "fuel", group: "교통", name: "주유", aliases: ["기름", "주유소", "휘발유", "경유", "연료"] },
  { id: "circle-parking", group: "교통", name: "주차", aliases: ["주차장", "주차비"] },
  { id: "plane", group: "교통", name: "비행기", aliases: ["항공", "항공권", "여행"] },
  { id: "ship", group: "교통", name: "배", aliases: ["선박", "여객선", "페리"] },
  { id: "bike", group: "교통", name: "자전거", aliases: ["따릉이", "라이딩"] },
  { id: "ticket", group: "교통", name: "승차권", aliases: ["표", "티켓", "기차표"] },
  { id: "route", group: "교통", name: "길 · 이동", aliases: ["경로", "출퇴근"] },
  // ── 주거 ──────────────────────────────────────────────
  { id: "house", group: "주거", name: "집", aliases: ["주거", "월세", "관리비", "홈", "home", "전세"], lucideAliases: ["home"] },
  { id: "building", group: "주거", name: "아파트", aliases: ["건물", "오피스텔", "빌라"] },
  { id: "key-round", group: "주거", name: "열쇠", aliases: ["보증금", "전세", "계약"] },
  { id: "zap", group: "주거", name: "전기", aliases: ["전기요금", "전기세", "번개"] },
  { id: "droplet", group: "주거", name: "수도", aliases: ["물", "수도요금", "수도세"] },
  { id: "flame", group: "주거", name: "가스", aliases: ["난방", "가스요금", "도시가스"] },
  { id: "wifi", group: "주거", name: "인터넷", aliases: ["와이파이", "통신", "인터넷요금"] },
  { id: "smartphone", group: "주거", name: "휴대폰", aliases: ["통신비", "핸드폰", "폰", "요금제"] },
  { id: "tv", group: "주거", name: "TV", aliases: ["티비", "방송", "케이블", "IPTV"] },
  { id: "sofa", group: "주거", name: "가구", aliases: ["인테리어", "소파"] },
  { id: "bed", group: "주거", name: "침대", aliases: ["가구", "침구"] },
  { id: "lamp", group: "주거", name: "조명", aliases: ["전등", "스탠드"] },
  { id: "wrench", group: "주거", name: "수리", aliases: ["공구", "수선", "AS"] },
  { id: "paint-roller", group: "주거", name: "인테리어", aliases: ["도배", "페인트", "리모델링"] },
  // ── 생활 ──────────────────────────────────────────────
  { id: "shopping-cart", group: "생활", name: "생활용품", aliases: ["마트", "장보기", "생필품"] },
  { id: "spray-can", group: "생활", name: "세제", aliases: ["청소", "세정제", "생활용품"] },
  { id: "washing-machine", group: "생활", name: "세탁", aliases: ["빨래", "세탁소", "코인빨래"] },
  { id: "scissors", group: "생활", name: "미용", aliases: ["미용실", "헤어", "이발", "커트"] },
  { id: "sparkles", group: "생활", name: "청소", aliases: ["깨끗", "정리", "클리닝"] },
  { id: "trash-2", group: "생활", name: "쓰레기", aliases: ["종량제", "분리수거"] },
  { id: "package", group: "생활", name: "택배", aliases: ["배송", "소포", "우체국"] },
  { id: "mail", group: "생활", name: "우편", aliases: ["편지", "등기"] },
  { id: "umbrella", group: "생활", name: "우산", aliases: ["비", "장마"] },
  { id: "baby", group: "생활", name: "육아", aliases: ["아기", "기저귀", "분유", "아이"] },
  { id: "dog", group: "생활", name: "강아지", aliases: ["반려견", "반려동물", "펫", "애견"] },
  { id: "cat", group: "생활", name: "고양이", aliases: ["반려묘", "반려동물", "펫", "냥이"] },
  { id: "paw-print", group: "생활", name: "반려동물", aliases: ["펫", "동물병원", "사료"] },
  { id: "flower", group: "생활", name: "꽃", aliases: ["꽃집", "화원", "꽃다발"] },
  { id: "sprout", group: "생활", name: "식물", aliases: ["화분", "가드닝", "텃밭"] },
  // ── 쇼핑 ──────────────────────────────────────────────
  { id: "shopping-bag", group: "쇼핑", name: "쇼핑", aliases: ["구매", "쇼핑백", "온라인쇼핑"] },
  { id: "shirt", group: "쇼핑", name: "옷", aliases: ["의류", "패션", "옷값"] },
  { id: "glasses", group: "쇼핑", name: "안경", aliases: ["렌즈", "안경점"] },
  { id: "watch", group: "쇼핑", name: "시계", aliases: ["손목시계"] },
  { id: "gem", group: "쇼핑", name: "보석", aliases: ["액세서리", "주얼리", "귀걸이", "반지"] },
  { id: "gift", group: "쇼핑", name: "선물", aliases: ["기념일", "생일선물", "선물하기"] },
  { id: "store", group: "쇼핑", name: "가게", aliases: ["상점", "매장", "편의점"] },
  { id: "laptop", group: "쇼핑", name: "전자기기", aliases: ["노트북", "컴퓨터", "가전"] },
  { id: "headphones", group: "쇼핑", name: "이어폰", aliases: ["헤드폰", "음향"] },
  { id: "camera", group: "쇼핑", name: "카메라", aliases: ["사진", "촬영"] },
  { id: "book", group: "쇼핑", name: "책", aliases: ["도서", "서점"] },
  { id: "backpack", group: "쇼핑", name: "가방", aliases: ["백팩", "잡화"] },
  // ── 건강 ──────────────────────────────────────────────
  { id: "heart-pulse", group: "건강", name: "병원", aliases: ["의료", "진료", "의원", "건강"] },
  { id: "hospital", group: "건강", name: "종합병원", aliases: ["응급", "입원"] },
  { id: "pill", group: "건강", name: "약", aliases: ["약국", "영양제", "처방"] },
  { id: "stethoscope", group: "건강", name: "진료", aliases: ["검진", "건강검진", "의원"] },
  { id: "syringe", group: "건강", name: "주사", aliases: ["예방접종", "백신"] },
  { id: "dumbbell", group: "건강", name: "운동", aliases: ["헬스", "피트니스", "PT", "체육관"] },
  { id: "activity", group: "건강", name: "활동", aliases: ["운동", "기록", "심박", "건강"] },
  { id: "heart", group: "건강", name: "건강", aliases: ["하트", "좋아요", "마음", "사랑"] },
  { id: "smile", group: "건강", name: "치과", aliases: ["치아", "스케일링", "미소"] },
  { id: "eye", group: "건강", name: "안과", aliases: ["시력", "눈"] },
  // ── 금융 ──────────────────────────────────────────────
  { id: "wallet", group: "금융", name: "지갑", aliases: ["급여", "월급", "용돈", "현금", "돈"] },
  { id: "banknote", group: "금융", name: "현금", aliases: ["돈", "지폐", "현금인출"] },
  { id: "coins", group: "금융", name: "동전", aliases: ["잔돈", "용돈", "포인트"] },
  { id: "piggy-bank", group: "금융", name: "저금", aliases: ["저축", "적금", "예금", "돼지저금통", "목표"] },
  { id: "credit-card", group: "금융", name: "카드", aliases: ["신용카드", "체크카드", "카드값"] },
  { id: "landmark", group: "금융", name: "은행", aliases: ["금융", "계좌", "송금"] },
  { id: "receipt", group: "금융", name: "영수증", aliases: ["세금", "공과금", "고지서"] },
  { id: "percent", group: "금융", name: "이자", aliases: ["할인", "금리", "수수료"] },
  { id: "trending-up", group: "금융", name: "투자", aliases: ["주식", "수익", "부수입", "재테크"] },
  { id: "chart-line", group: "금융", name: "주식", aliases: ["증권", "투자", "차트"] },
  { id: "hand-coins", group: "금융", name: "대출", aliases: ["빚", "갚기", "할부", "상환"] },
  { id: "shield-check", group: "금융", name: "보험", aliases: ["보장", "보험료", "실비"] },
  { id: "calculator", group: "금융", name: "세금", aliases: ["정산", "연말정산", "계산"] },
  { id: "briefcase", group: "금융", name: "회사", aliases: ["업무", "사업", "출장", "일", "직장", "월급"] },
  { id: "arrow-left-right", group: "금융", name: "이체", aliases: ["송금", "계좌이체"] },
  { id: "repeat", group: "금융", name: "구독", aliases: ["정기결제", "정기", "멤버십", "자동결제"] },
  // ── 여가 ──────────────────────────────────────────────
  { id: "film", group: "여가", name: "영화", aliases: ["극장", "문화", "영화관"] },
  { id: "clapperboard", group: "여가", name: "영상", aliases: ["OTT", "넷플릭스", "동영상"] },
  { id: "music", group: "여가", name: "음악", aliases: ["스트리밍", "멜론", "공연", "노래"] },
  { id: "gamepad-2", group: "여가", name: "게임", aliases: ["게임기", "콘솔", "PC방"] },
  { id: "drama", group: "여가", name: "공연", aliases: ["연극", "뮤지컬", "문화"] },
  { id: "palette", group: "여가", name: "미술", aliases: ["전시", "그림", "취미"] },
  { id: "book-open", group: "여가", name: "독서", aliases: ["책", "도서", "전자책"] },
  { id: "tent", group: "여가", name: "캠핑", aliases: ["야외", "글램핑"] },
  { id: "mountain", group: "여가", name: "등산", aliases: ["산", "하이킹"] },
  { id: "waves-horizontal", group: "여가", name: "수영", aliases: ["바다", "물놀이"], lucideAliases: ["waves"] },
  { id: "trophy", group: "여가", name: "스포츠", aliases: ["경기", "대회", "관람"] },
  { id: "guitar", group: "여가", name: "악기", aliases: ["기타", "음악", "레슨"] },
  { id: "party-popper", group: "여가", name: "파티", aliases: ["모임", "축하"] },
  { id: "dice-5", group: "여가", name: "보드게임", aliases: ["주사위", "놀이"] },
  { id: "puzzle", group: "여가", name: "취미", aliases: ["퍼즐", "놀이"] },
  // ── 여행 ──────────────────────────────────────────────
  { id: "luggage", group: "여행", name: "여행", aliases: ["짐", "캐리어", "휴가"] },
  { id: "hotel", group: "여행", name: "숙소", aliases: ["호텔", "숙박", "펜션", "에어비앤비"] },
  { id: "map", group: "여행", name: "관광", aliases: ["지도", "투어"] },
  { id: "map-pin", group: "여행", name: "장소", aliases: ["위치", "핀"] },
  { id: "globe", group: "여행", name: "해외", aliases: ["외국", "해외여행", "환전"] },
  { id: "tree-palm", group: "여행", name: "휴양", aliases: ["바다", "리조트", "휴가"] },
  // ── 교육 ──────────────────────────────────────────────
  { id: "graduation-cap", group: "교육", name: "교육", aliases: ["학비", "학원", "대학", "등록금"] },
  { id: "school", group: "교육", name: "학교", aliases: ["등록금"] },
  { id: "pencil", group: "교육", name: "문구", aliases: ["필기", "학용품"] },
  { id: "notebook-pen", group: "교육", name: "공부", aliases: ["강의", "수업", "인강"] },
  { id: "library", group: "교육", name: "도서관", aliases: ["열람실", "독서실"] },
  { id: "languages", group: "교육", name: "어학", aliases: ["외국어", "영어", "학원"] },
  // ── 경조사 ────────────────────────────────────────────
  { id: "cake", group: "경조사", name: "생일", aliases: ["기념일", "파티"] },
  { id: "heart-handshake", group: "경조사", name: "경조사", aliases: ["축의금", "부의금", "조의금", "결혼식", "장례식"] },
  { id: "hand-heart", group: "경조사", name: "기부", aliases: ["후원", "헌금", "기부금"] },
  { id: "users", group: "경조사", name: "모임", aliases: ["회비", "친구", "동호회", "계모임"] },
  { id: "church", group: "경조사", name: "종교", aliases: ["헌금", "교회", "성당", "절"] },
  { id: "mail-open", group: "경조사", name: "청첩장", aliases: ["초대", "결혼"] },
  // ── 기타 ──────────────────────────────────────────────
  { id: "tag", group: "기타", name: "태그", aliases: ["기타", "분류", "꼬리표"] },
  { id: "star", group: "기타", name: "별", aliases: ["즐겨찾기", "중요"] },
  { id: "bookmark", group: "기타", name: "책갈피", aliases: ["표시", "저장"] },
  { id: "box", group: "기타", name: "상자", aliases: ["물건", "기타"] },
  { id: "folder", group: "기타", name: "폴더", aliases: ["묶음", "기타"] },
  { id: "ellipsis", group: "기타", name: "그 밖", aliases: ["기타", "그외", "더보기"] },
];

/** id → lucide 컴포넌트(세트 안만 — 세트 밖 저장 값은 lucide-react/dynamic 의 DynamicIcon 으로 그린다) */
export const CATEGORY_ICON_COMPONENTS: Readonly<Record<string, LucideIcon>> = {
  "utensils": UtensilsIcon,
  "utensils-crossed": UtensilsCrossedIcon,
  "chef-hat": ChefHatIcon,
  "soup": SoupIcon,
  "salad": SaladIcon,
  "sandwich": SandwichIcon,
  "pizza": PizzaIcon,
  "hamburger": HamburgerIcon,
  "drumstick": DrumstickIcon,
  "beef": BeefIcon,
  "fish": FishIcon,
  "egg-fried": EggFriedIcon,
  "croissant": CroissantIcon,
  "cake-slice": CakeSliceIcon,
  "ice-cream-cone": IceCreamConeIcon,
  "cookie": CookieIcon,
  "candy": CandyIcon,
  "apple": AppleIcon,
  "carrot": CarrotIcon,
  "popcorn": PopcornIcon,
  "milk": MilkIcon,
  "wheat": WheatIcon,
  "shopping-basket": ShoppingBasketIcon,
  "coffee": CoffeeIcon,
  "cup-soda": CupSodaIcon,
  "glass-water": GlassWaterIcon,
  "beer": BeerIcon,
  "wine": WineIcon,
  "martini": MartiniIcon,
  "bean": BeanIcon,
  "bus": BusIcon,
  "train-front": TrainFrontIcon,
  "tram-front": TramFrontIcon,
  "car": CarIcon,
  "car-taxi-front": CarTaxiFrontIcon,
  "fuel": FuelIcon,
  "circle-parking": CircleParkingIcon,
  "plane": PlaneIcon,
  "ship": ShipIcon,
  "bike": BikeIcon,
  "ticket": TicketIcon,
  "route": RouteIcon,
  "house": HouseIcon,
  "building": BuildingIcon,
  "key-round": KeyRoundIcon,
  "zap": ZapIcon,
  "droplet": DropletIcon,
  "flame": FlameIcon,
  "wifi": WifiIcon,
  "smartphone": SmartphoneIcon,
  "tv": TvIcon,
  "sofa": SofaIcon,
  "bed": BedIcon,
  "lamp": LampIcon,
  "wrench": WrenchIcon,
  "paint-roller": PaintRollerIcon,
  "shopping-cart": ShoppingCartIcon,
  "spray-can": SprayCanIcon,
  "washing-machine": WashingMachineIcon,
  "scissors": ScissorsIcon,
  "sparkles": SparklesIcon,
  "trash-2": Trash2Icon,
  "package": PackageIcon,
  "mail": MailIcon,
  "umbrella": UmbrellaIcon,
  "baby": BabyIcon,
  "dog": DogIcon,
  "cat": CatIcon,
  "paw-print": PawPrintIcon,
  "flower": FlowerIcon,
  "sprout": SproutIcon,
  "shopping-bag": ShoppingBagIcon,
  "shirt": ShirtIcon,
  "glasses": GlassesIcon,
  "watch": WatchIcon,
  "gem": GemIcon,
  "gift": GiftIcon,
  "store": StoreIcon,
  "laptop": LaptopIcon,
  "headphones": HeadphonesIcon,
  "camera": CameraIcon,
  "book": BookIcon,
  "backpack": BackpackIcon,
  "heart-pulse": HeartPulseIcon,
  "hospital": HospitalIcon,
  "pill": PillIcon,
  "stethoscope": StethoscopeIcon,
  "syringe": SyringeIcon,
  "dumbbell": DumbbellIcon,
  "activity": ActivityIcon,
  "heart": HeartIcon,
  "smile": SmileIcon,
  "eye": EyeIcon,
  "wallet": WalletIcon,
  "banknote": BanknoteIcon,
  "coins": CoinsIcon,
  "piggy-bank": PiggyBankIcon,
  "credit-card": CreditCardIcon,
  "landmark": LandmarkIcon,
  "receipt": ReceiptIcon,
  "percent": PercentIcon,
  "trending-up": TrendingUpIcon,
  "chart-line": ChartLineIcon,
  "hand-coins": HandCoinsIcon,
  "shield-check": ShieldCheckIcon,
  "calculator": CalculatorIcon,
  "briefcase": BriefcaseIcon,
  "arrow-left-right": ArrowLeftRightIcon,
  "repeat": RepeatIcon,
  "film": FilmIcon,
  "clapperboard": ClapperboardIcon,
  "music": MusicIcon,
  "gamepad-2": Gamepad2Icon,
  "drama": DramaIcon,
  "palette": PaletteIcon,
  "book-open": BookOpenIcon,
  "tent": TentIcon,
  "mountain": MountainIcon,
  "waves-horizontal": WavesHorizontalIcon,
  "trophy": TrophyIcon,
  "guitar": GuitarIcon,
  "party-popper": PartyPopperIcon,
  "dice-5": Dice5Icon,
  "puzzle": PuzzleIcon,
  "luggage": LuggageIcon,
  "hotel": HotelIcon,
  "map": MapIcon,
  "map-pin": MapPinIcon,
  "globe": GlobeIcon,
  "tree-palm": TreePalmIcon,
  "graduation-cap": GraduationCapIcon,
  "school": SchoolIcon,
  "pencil": PencilIcon,
  "notebook-pen": NotebookPenIcon,
  "library": LibraryIcon,
  "languages": LanguagesIcon,
  "cake": CakeIcon,
  "heart-handshake": HeartHandshakeIcon,
  "hand-heart": HandHeartIcon,
  "users": UsersIcon,
  "church": ChurchIcon,
  "mail-open": MailOpenIcon,
  "tag": TagIcon,
  "star": StarIcon,
  "bookmark": BookmarkIcon,
  "box": BoxIcon,
  "folder": FolderIcon,
  "ellipsis": EllipsisIcon,
};
// @generated:end

/** 묶음 이름 — "식비" · "카페" … */
export type CategoryIconGroup = (typeof CATEGORY_ICON_GROUPS)[number];

export interface CategoryIcon {
  /** lucide 이름(kebab) — 저장 값 */
  readonly id: string;
  /** 묶음 */
  readonly group: CategoryIconGroup;
  /** 한국어 이름 — 칸의 이름 · 트리거의 값 글. 세트 안에서 겹치지 않는다 */
  readonly name: string;
  /** 찾는 말 — 이름 말고 이 아이콘으로 찾을 말("월세" → 집) */
  readonly aliases: readonly string[];
  /** 같은 아이콘의 다른 lucide 이름(옛 이름) — 저장 값이 이 이름이어도 이 아이콘을 고른 것으로 본다 */
  readonly lucideAliases?: readonly string[];
}

// 찾는 말 · 표의 글 — 소문자로 바꾸고 공백을 모두 뺀다(웹 · 앱이 같은 규칙으로)
const normalize = (value: string) => value.toLowerCase().replace(/\s+/g, "");

// 저장 값 → 세트의 한 줄(id 와 lucideAliases 모두)
const BY_ID = new Map<string, CategoryIcon>();
for (const icon of CATEGORY_ICONS) {
  BY_ID.set(icon.id, icon);
  for (const alias of icon.lucideAliases ?? []) BY_ID.set(alias, icon);
}

// 아이콘마다 찾는 글(이름 · 찾는 말 · id) — 표 차례 그대로
const HAYSTACK = CATEGORY_ICONS.map((icon) => ({ icon, keys: [icon.name, ...icon.aliases, icon.id].map(normalize) }));

/** 저장 값(lucide 이름) → 세트의 한 줄. id 또는 lucideAliases 로 찾고, 세트 밖 · 빈 값이면 null */
function findCategoryIcon(id: string | null | undefined): CategoryIcon | null {
  const key = id?.trim() ?? "";
  if (key === "") return null;
  return BY_ID.get(key) ?? null;
}

/** 찾는 말 → 걸린 아이콘(세트 차례). 이름 · 찾는 말 · id 의 부분 일치 — 소문자로 바꾸고 공백을 뺀 뒤. 빈 찾는 말이면 세트 전체 */
function searchCategoryIcons(query: string): readonly CategoryIcon[] {
  const q = normalize(query);
  if (q === "") return CATEGORY_ICONS;
  return HAYSTACK.filter(({ keys }) => keys.some((k) => k.includes(q))).map(({ icon }) => icon);
}

export { findCategoryIcon, searchCategoryIcons };
