#!/usr/bin/env node
// Porest Design — multi-page static documentation site
//
// 출력: exports/site/
//   index.html                      Landing (브랜드 정체성 + 핵심 가치)
//   tokens/{colors,typography,spacing,radius,shadows,motion,breakpoints,z-index}.html
//   assets/site.css                 사이트 전용 layout CSS
//   assets/tokens.css               3-brand 통합 (`:root` + `[data-brand="hr|desk"]`)
//   assets/site.js                  brand toggle / theme toggle / mobile nav
//
// 외부 의존성 0 — vanilla Node + 기존 build-tailwind-v4 산출물 재사용.
// Phase 1 — 사이트 골격 + Landing + Token 페이지.
// Phase 2 (미래) — 컴포넌트 페이지. Phase 3 — 조합 layout.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

// preview.html의 데모 render 함수 + CSS 재사용 — single source of truth
import {
  brandProfile,
  pageCss as previewPageCss,
  parseTokensFromCss,
  renderButtonGallery,
  renderListingDetail,
  renderCalendar,
  renderEmptyState,
  renderModal,
  renderToasts,
  renderSkeleton,
  renderForm,
  renderBatchV67,
  renderShadcnNav,
  renderShadcnInput,
  renderShadcnDisclose,
  renderShadcnData,
  renderShadcnExtras,
  renderBatchV73V78,
} from "./build-preview-html.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "exports/site");

function escape(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

// ============================================================
// 1. tokens 통합 — 3 브랜드 단일 CSS
// ============================================================

// 토큰 빌드 결과를 두 형태로 분리:
//   - rootCss: 외부 <link> stylesheet — 브라우저가 즉시 적용 (FOUC 방지, layout 색상)
//   - tailwindBlock: 인라인 <style type="text/tailwindcss"> — Tailwind v4 CDN이 @theme 읽어 utility 생성
function buildTokens() {
  const def = readFileSync(resolve(ROOT, "exports/tokens.css"), "utf8");
  const hr = readFileSync(resolve(ROOT, "exports/tokens.hr.css"), "utf8");
  const desk = readFileSync(resolve(ROOT, "exports/tokens.desk.css"), "utf8");

  // Default에 brand fallback 4 토큰 추가
  const defaultWithFallback = def.replace(
    /@theme\s*\{/,
    "@theme {\n  /* Brand fallback — Default = neutral, no specific accent */\n  --color-primary: #1a1f2e;\n  --color-primary-light: #4a5568;\n  --color-border-focus: #1a1f2e;\n  --color-border-focus-light: #4a5568;"
  );

  // @theme 내용 추출 → :root 미러 (브라우저가 즉시 적용)
  const themeMatch = /@theme\s*\{([\s\S]*?)\n\}/.exec(defaultWithFallback);
  const themeContent = themeMatch ? themeMatch[1] : "";
  const rootBlock = `:root, [data-brand="default"] {${themeContent}\n}`;

  // brand override (@theme 외부, CSS variable만 재정의)
  const brandOverride = (cssText, attr) => {
    const tokens = [];
    const re = /^\s*--color-(primary|primary-light|border-focus|border-focus-light)(-dark)?:\s*([^;]+);/gm;
    let m;
    while ((m = re.exec(cssText)) !== null) {
      const name = `--color-${m[1]}${m[2] || ""}`;
      tokens.push(`  ${name}: ${m[3].trim()};`);
    }
    return `[data-brand="${attr}"] {\n${tokens.join("\n")}\n}`;
  };

  const darkBlock = [
    "[data-theme=\"dark\"] {",
    "  --color-bg-page: var(--color-bg-page-dark);",
    "  --color-surface-default: var(--color-surface-default-dark);",
    "  --color-surface-input: var(--color-surface-input-dark);",
    "  --color-text-primary: var(--color-text-primary-dark);",
    "  --color-text-secondary: var(--color-text-secondary-dark);",
    "  --color-text-tertiary: var(--color-text-tertiary-dark);",
    "  --color-text-disabled: var(--color-text-disabled-dark);",
    "  --color-border-default: var(--color-border-default-dark);",
    "  --color-border-strong: var(--color-border-strong-dark);",
    "  --color-success: var(--color-success-light);",
    "  --color-error: var(--color-error-light);",
    "  --color-warning: var(--color-warning-light);",
    "  --color-info: var(--color-info-light);",
    "  --shadow-sm: var(--shadow-sm-dark);",
    "  --shadow-md: var(--shadow-md-dark);",
    "  --shadow-lg: var(--shadow-lg-dark);",
    "  --shadow-xl: var(--shadow-xl-dark);",
    "}",
    "[data-theme=\"dark\"][data-brand=\"hr\"], [data-theme=\"dark\"] [data-brand=\"hr\"] {",
    "  --color-primary: var(--color-primary-light);",
    "  --color-border-focus: var(--color-border-focus-light);",
    "}",
    "[data-theme=\"dark\"][data-brand=\"desk\"], [data-theme=\"dark\"] [data-brand=\"desk\"] {",
    "  --color-primary: var(--color-primary-light);",
    "  --color-border-focus: var(--color-border-focus-light);",
    "}",
  ].join("\n");

  // === rootCss: 외부 stylesheet ===
  const rootCss = [
    "/* Generated by scripts/build-site.mjs — :root fallback (FOUC 방지) */",
    "/* Tailwind v4 CDN이 처리하기 전에도 브라우저가 즉시 CSS variable 적용 */",
    "",
    rootBlock,
    "",
    brandOverride(hr, "hr"),
    "",
    brandOverride(desk, "desk"),
    "",
    darkBlock,
  ].join("\n");

  // === tailwindBlock: 인라인 <style type="text/tailwindcss"> ===
  // Tailwind v4 CDN이 @theme 블록을 읽어 utility class(.bg-primary 등) 생성.
  // brand override / dark mode block도 같이 포함 — Tailwind가 인라인 style 안에서 모두 인식.
  const tailwindBlock = [
    defaultWithFallback,  // @theme {} 블록 그대로
    "",
    brandOverride(hr, "hr"),
    "",
    brandOverride(desk, "desk"),
    "",
    darkBlock,
  ].join("\n");

  return { rootCss, tailwindBlock };
}


// ============================================================
// 2. 사이트 layout CSS (sidebar / topbar / content)
// ============================================================

function siteCss() {
  return `
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  font-family: var(--font-sans);
  margin: 0;
  background: var(--color-bg-page);
  color: var(--color-text-primary);
  font-size: var(--text-body);
  line-height: var(--text-body--line-height);
  letter-spacing: var(--text-body--letter-spacing);
}

/* === Layout === */
.app { display: grid; grid-template-columns: 260px 1fr; min-height: 100vh; }
.sidebar {
  border-inline-end: 1px solid var(--color-border-default);
  background: var(--color-surface-default);
  padding: 24px 16px;
  position: sticky;
  top: 0;
  height: 100vh;
  overflow-y: auto;
}
.main { min-width: 0; }
.topbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 32px;
  border-bottom: 1px solid var(--color-border-default);
  background: var(--color-surface-default);
  position: sticky; top: 0; z-index: 100;
}
.content {
  padding: 48px 56px 96px;
  max-width: 920px;
}

/* === Sidebar === */
.brand-row { display: flex; align-items: center; gap: 8px; padding: 4px 8px 24px; }
.brand-row strong { font-size: var(--text-heading-md); font-weight: 700; color: var(--color-primary); letter-spacing: -0.01em; }
.brand-row .brand-tag { font-size: var(--text-caption-sm); padding: 2px 8px; border-radius: var(--radius-sm); background: var(--color-surface-input); color: var(--color-text-tertiary); font-weight: 600; }

.nav-section { margin-bottom: 24px; }
.nav-eyebrow {
  font-size: var(--text-caption-sm);
  font-weight: 700;
  color: var(--color-text-tertiary);
  text-transform: uppercase;
  letter-spacing: 0.06em;
  padding: 0 12px;
  margin-bottom: 8px;
}
.nav-list { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 2px; }
.nav-list a {
  display: block;
  padding: 6px 12px;
  border-radius: var(--radius-sm);
  color: var(--color-text-secondary);
  text-decoration: none;
  font-size: var(--text-caption-md);
  transition: all var(--motion-duration-fast) var(--motion-ease-out);
}
.nav-list a:hover { background: var(--color-surface-input); color: var(--color-text-primary); }
.nav-list a[aria-current="page"] {
  color: var(--color-primary);
  background: color-mix(in srgb, var(--color-primary) 8%, transparent);
  font-weight: 600;
}
.nav-list a.disabled { color: var(--color-text-disabled); cursor: not-allowed; pointer-events: none; }
.nav-list a .badge-soon { font-size: 10px; padding: 1px 6px; background: var(--color-surface-input); border-radius: var(--radius-full); margin-inline-start: 6px; color: var(--color-text-tertiary); font-weight: 500; }

/* === Topbar controls === */
.crumbs { font-size: var(--text-caption); color: var(--color-text-tertiary); display: flex; align-items: center; gap: 6px; }
.crumbs a { color: var(--color-text-secondary); text-decoration: none; }
.crumbs a:hover { color: var(--color-text-primary); }
.crumbs span { color: var(--color-text-tertiary); }

.controls { display: flex; align-items: center; gap: 8px; flex-shrink: 0; }
.brand-switch { display: inline-flex; padding: 3px; background: var(--color-surface-input); border-radius: var(--radius-full); gap: 2px; flex-shrink: 0; }
.sidebar .brand-switch { display: none; margin: 0 4px 16px; }
.brand-switch button {
  border: 0; background: transparent;
  padding: 4px 12px;
  border-radius: var(--radius-full);
  font-size: var(--text-caption-sm); font-weight: 600;
  cursor: pointer;
  color: var(--color-text-secondary);
  transition: all var(--motion-duration-fast) var(--motion-ease-out);
  white-space: nowrap;
}
.brand-switch button[aria-pressed="true"] {
  background: var(--color-surface-default);
  color: var(--color-primary);
  box-shadow: var(--shadow-sm);
}
.theme-toggle {
  border: 1px solid var(--color-border-default);
  background: var(--color-surface-default);
  border-radius: var(--radius-full);
  padding: 4px 10px;
  cursor: pointer;
  font-size: var(--text-caption-sm); font-weight: 500;
  color: var(--color-text-secondary);
  display: inline-flex; align-items: center; gap: 6px;
  flex-shrink: 0;
  white-space: nowrap;
}
.theme-toggle:hover { color: var(--color-text-primary); }
.theme-toggle-label { display: inline; }

/* === Content typography === */
.content h1 {
  font-size: var(--text-heading-xl);
  font-weight: 700;
  margin: 0 0 8px;
  letter-spacing: -0.02em;
  line-height: 1.1;
}
.content .lede {
  font-size: var(--text-body-md);
  color: var(--color-text-secondary);
  margin: 0 0 40px;
  line-height: 1.6;
}
.content h2 {
  font-size: var(--text-heading-lg);
  font-weight: 700;
  margin: 56px 0 16px;
  padding-bottom: 12px;
  border-bottom: 1px solid var(--color-border-default);
  letter-spacing: -0.01em;
}
.content h3 { font-size: var(--text-heading-md); font-weight: 600; margin: 32px 0 12px; }
.content h4 { font-size: var(--text-heading-sm); font-weight: 600; margin: 24px 0 8px; color: var(--color-text-secondary); }
.content p { margin: 12px 0; color: var(--color-text-primary); }
.content code {
  background: var(--color-surface-input);
  padding: 2px 6px;
  border-radius: var(--radius-sm);
  font-family: ui-monospace, "SF Mono", Menlo, monospace;
  font-size: 0.9em;
}
.content pre {
  margin: 16px 0;
  padding: 16px 20px;
  border-radius: var(--radius-md);
  overflow-x: auto;
  background: var(--color-surface-default);
  border: 1px solid var(--color-border-default);
  font-size: 13px;
  line-height: 1.6;
}
.content pre code { background: transparent; padding: 0; font-size: inherit; }
.content table { width: 100%; border-collapse: collapse; font-size: var(--text-caption); margin: 16px 0; }
.content thead { background: var(--color-surface-input); }
.content th, .content td { padding: 10px 12px; text-align: start; border-bottom: 1px solid var(--color-border-default); }
.content th { font-weight: 600; color: var(--color-text-secondary); }

/* === Hero (landing) === */
.hero {
  padding: 80px 0 48px;
  border-bottom: 1px solid var(--color-border-default);
  margin-bottom: 64px;
}
.hero-eyebrow {
  display: inline-block;
  font-size: var(--text-caption-sm);
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-weight: 700;
  color: var(--color-primary);
  margin-bottom: 12px;
}
.hero h1 {
  font-size: clamp(32px, 5vw, 48px);
  font-weight: 800;
  letter-spacing: -0.03em;
  line-height: 1.05;
  margin: 0 0 20px;
}
.hero p {
  font-size: var(--text-body-md);
  line-height: 1.6;
  max-width: 640px;
  color: var(--color-text-secondary);
  margin: 0 0 32px;
}
.hero-actions { display: flex; gap: 12px; flex-wrap: wrap; }

.btn {
  display: inline-flex; align-items: center; gap: 6px;
  padding: 10px 20px;
  border-radius: var(--radius-md);
  font-size: var(--text-body); font-weight: 600;
  cursor: pointer; border: 0;
  font-family: inherit;
  text-decoration: none;
  transition: all var(--motion-duration-fast) var(--motion-ease-out);
}
.btn--primary { background: var(--color-primary); color: var(--color-text-on-accent); }
.btn--primary:hover { box-shadow: var(--shadow-md); }
.btn--outlined { background: transparent; color: var(--color-primary); border: 1px solid var(--color-primary); }
.btn--outlined:hover { background: color-mix(in srgb, var(--color-primary) 6%, transparent); }
.btn--ghost { background: transparent; color: var(--color-text-primary); }
.btn--ghost:hover { background: var(--color-surface-input); }

/* === Brand identity cards === */
.identity-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 16px;
  margin: 32px 0;
}
.identity-card {
  background: var(--color-surface-default);
  border: 1px solid var(--color-border-default);
  border-radius: var(--radius-lg);
  padding: 24px;
  display: flex; flex-direction: column; gap: 12px;
}
.identity-tag {
  display: inline-block;
  font-size: var(--text-caption-sm);
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--color-text-tertiary);
}
.identity-card h3 { margin: 0; font-size: var(--text-heading-sm); }
.identity-card p { margin: 0; color: var(--color-text-secondary); font-size: var(--text-caption-md); line-height: 1.6; }
.identity-swatch {
  width: 56px; height: 56px;
  border-radius: var(--radius-md);
  display: flex; align-items: center; justify-content: center;
  color: white; font-weight: 700; font-size: 18px;
  box-shadow: var(--shadow-sm);
}

/* === Token page utilities === */
.swatch-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 12px; margin: 16px 0 32px; }
.swatch {
  background: var(--color-surface-default);
  border: 1px solid var(--color-border-default);
  border-radius: var(--radius-md);
  overflow: hidden;
  display: flex;
  flex-direction: column;
}
.swatch-color { height: 80px; }
.swatch-meta { padding: 12px; display: flex; flex-direction: column; gap: 2px; }
.swatch-name { font-size: var(--text-caption-md); font-weight: 600; font-family: ui-monospace, monospace; }
.swatch-hex { font-size: var(--text-caption-sm); color: var(--color-text-tertiary); font-family: ui-monospace, monospace; }

.spec-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 16px;
  margin: 16px 0;
}
.spec-card {
  background: var(--color-surface-default);
  border: 1px solid var(--color-border-default);
  border-radius: var(--radius-lg);
  padding: 20px;
}
.spec-card h4 { margin: 0 0 12px; font-size: var(--text-caption-md); color: var(--color-text-tertiary); text-transform: uppercase; letter-spacing: 0.06em; font-family: ui-monospace, monospace; }

.type-row {
  display: grid; grid-template-columns: 200px 1fr; gap: 24px;
  align-items: baseline;
  padding: 20px 0;
  border-bottom: 1px solid var(--color-border-default);
}
.type-row:last-child { border-bottom: 0; }
.type-row .meta { font-size: var(--text-caption-sm); color: var(--color-text-tertiary); font-family: ui-monospace, monospace; line-height: 1.6; }
.type-row .meta strong { color: var(--color-text-primary); display: block; margin-bottom: 4px; }
.type-row .sample { color: var(--color-text-primary); }

.spacing-row {
  display: grid; grid-template-columns: 80px 100px 1fr; gap: 16px;
  align-items: center;
  padding: 14px 0;
  border-bottom: 1px solid var(--color-border-default);
}
.spacing-row:last-child { border-bottom: 0; }
.spacing-name { font-family: ui-monospace, monospace; font-size: var(--text-caption-md); font-weight: 600; }
.spacing-value { font-size: var(--text-caption); color: var(--color-text-tertiary); font-family: ui-monospace, monospace; }
.spacing-bar { height: 24px; background: color-mix(in srgb, var(--color-primary) 30%, transparent); border-radius: var(--radius-sm); }

.radius-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: 16px; margin: 16px 0; }
.radius-card { background: var(--color-surface-default); padding: 20px; display: flex; flex-direction: column; align-items: center; gap: 12px; border: 1px solid var(--color-border-default); border-radius: var(--radius-md); }
.radius-shape { width: 80px; height: 80px; background: var(--color-primary); }

.shadow-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 24px; margin: 24px 0; padding: 32px; background: var(--color-bg-page); border-radius: var(--radius-md); }
.shadow-card { background: var(--color-surface-default); border-radius: var(--radius-md); padding: 24px; text-align: center; }

.motion-card { background: var(--color-surface-default); border: 1px solid var(--color-border-default); border-radius: var(--radius-md); padding: 20px; display: flex; flex-direction: column; gap: 12px; align-items: center; }
.motion-name { font-family: ui-monospace, monospace; font-size: var(--text-caption-md); font-weight: 600; }
.motion-value { font-size: var(--text-caption-sm); color: var(--color-text-tertiary); font-family: ui-monospace, monospace; }
.motion-demo { width: 56px; height: 56px; border-radius: var(--radius-md); background: var(--color-primary); }

@keyframes site-fade-in { from { opacity: 0 } to { opacity: 1 } }
@keyframes site-spin { from { transform: rotate(0deg) } to { transform: rotate(360deg) } }

.bp-row { display: grid; grid-template-columns: 120px 100px 1fr; gap: 16px; padding: 14px 0; border-bottom: 1px solid var(--color-border-default); align-items: center; }
.bp-row:last-child { border-bottom: 0; }
.bp-name { font-family: ui-monospace, monospace; font-weight: 600; }
.bp-value { color: var(--color-text-tertiary); font-family: ui-monospace, monospace; font-size: var(--text-caption); }
.bp-note { color: var(--color-text-secondary); font-size: var(--text-caption-md); }

.zindex-stack { position: relative; height: 280px; background: var(--color-bg-page); border-radius: var(--radius-md); padding: 16px; overflow: hidden; }
.zindex-card {
  position: absolute;
  background: var(--color-surface-default);
  border: 1px solid var(--color-border-default);
  border-radius: var(--radius-md);
  padding: 12px 16px;
  box-shadow: var(--shadow-md);
  font-size: var(--text-caption);
  font-family: ui-monospace, monospace;
  font-weight: 600;
}

/* === Component pages === */
.component-meta { display: flex; gap: 16px; margin: 16px 0 32px; padding-bottom: 16px; border-bottom: 1px solid var(--color-border-default); flex-wrap: wrap; }
.component-meta a {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 6px 12px;
  border: 1px solid var(--color-border-default);
  border-radius: var(--radius-md);
  font-size: var(--text-caption);
  color: var(--color-text-secondary);
  text-decoration: none;
  background: var(--color-surface-default);
  transition: all var(--motion-duration-fast) var(--motion-ease-out);
}
.component-meta a:hover { color: var(--color-primary); border-color: var(--color-primary); }
.component-meta a.tag {
  background: color-mix(in srgb, var(--color-primary) 8%, transparent);
  border-color: transparent;
  color: var(--color-primary);
  font-weight: 600;
  pointer-events: none;
}

.example-block {
  margin: 16px 0 32px;
  border: 1px solid var(--color-border-default);
  border-radius: var(--radius-md);
  overflow: hidden;
  background: var(--color-surface-default);
}
.example-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 16px;
  background: var(--color-surface-input);
  border-bottom: 1px solid var(--color-border-default);
}
.example-tabs { display: inline-flex; gap: 0; }
.example-tab {
  font-size: var(--text-caption-sm);
  font-weight: 600;
  padding: 4px 12px;
  background: transparent;
  border: 0;
  border-radius: var(--radius-sm);
  color: var(--color-text-secondary);
  cursor: pointer;
  font-family: inherit;
  text-transform: uppercase;
  letter-spacing: 0.04em;
}
.example-tab[aria-selected="true"] { background: var(--color-surface-default); color: var(--color-primary); box-shadow: var(--shadow-sm); }
.example-copy {
  border: 0;
  background: transparent;
  cursor: pointer;
  font-size: var(--text-caption-sm);
  color: var(--color-text-secondary);
  font-family: inherit;
  padding: 4px 8px;
  border-radius: var(--radius-sm);
}
.example-copy:hover { color: var(--color-text-primary); background: var(--color-surface-default); }
.example-copy.copied { color: var(--color-success); }
.example-block pre { margin: 0; padding: 16px 20px; background: transparent; border: 0; border-radius: 0; }
.example-block pre code { background: transparent; padding: 0; }
.example-label { font-size: var(--text-caption-sm); color: var(--color-text-tertiary); padding: 6px 16px 12px; font-style: italic; }
.example-preview { padding: 32px 24px; background: var(--color-bg-page); min-height: 120px; display: flex; align-items: center; justify-content: center; }
.example-preview > .preview-frame { width: 100%; max-width: 600px; }
.example-code { background: var(--color-surface-default); }

.callout {
  display: flex;
  gap: 12px;
  padding: 12px 16px;
  border-inline-start: 3px solid var(--color-primary);
  background: color-mix(in srgb, var(--color-primary) 6%, transparent);
  border-radius: 0 var(--radius-md) var(--radius-md) 0;
  margin: 16px 0;
  font-size: var(--text-caption-md);
}
.callout strong { color: var(--color-primary); }

/* === Mobile === */
.mobile-toggle { display: none; }
.mobile-overlay { display: none; }
@media (max-width: 880px) {
  .app { grid-template-columns: 1fr; }
  .sidebar { position: fixed; inset: 0 30% 0 0; z-index: 200; transform: translateX(-100%); transition: transform var(--motion-duration-base) var(--motion-ease-out); box-shadow: var(--shadow-xl); }
  .sidebar[data-open="true"] { transform: translateX(0); }
  .topbar { padding: 12px 16px; gap: 8px; }
  .content { padding: 32px 16px 64px; }
  .mobile-toggle { display: inline-flex; }
  .mobile-overlay[data-open] { display: block; position: fixed; inset: 0; background: var(--overlay-dim-light); z-index: 150; }
  /* 좁은 viewport — crumbs 줄임, theme 라벨 숨김, brand-switch 컴팩트 */
  .crumbs { min-width: 0; overflow: hidden; }
  .crumbs > a:not(:last-child), .crumbs > span:not(:last-child) { display: none; }
  .theme-toggle-label { display: none; }
  .theme-toggle { padding: 4px 8px; }
  .brand-switch button { padding: 4px 8px; }
}
@media (max-width: 600px) {
  /* 더 좁아지면 topbar brand-switch 숨김 — sidebar 안에서 표시 */
  .topbar .brand-switch { display: none; }
  .sidebar .brand-switch { display: inline-flex; align-self: flex-start; }
}
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}
`;
}

// ============================================================
// 3. 사이트 JS — brand toggle / theme toggle / mobile nav
// ============================================================

function siteJs() {
  return `
(function() {
  // Theme toggle
  function applyTheme(t) { document.documentElement.setAttribute("data-theme", t); }
  function getTheme() {
    try { return localStorage.getItem("porest-theme") || (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"); }
    catch(e) { return "light"; }
  }
  applyTheme(getTheme());
  document.addEventListener("click", function(e) {
    var btn = e.target.closest(".theme-toggle");
    if (!btn) return;
    var c = document.documentElement.getAttribute("data-theme");
    var n = c === "dark" ? "light" : "dark";
    applyTheme(n);
    try { localStorage.setItem("porest-theme", n); } catch(e) {}
  });

  // Brand toggle
  function applyBrand(b) {
    document.documentElement.setAttribute("data-brand", b);
    document.querySelectorAll(".brand-switch button").forEach(function(btn) {
      btn.setAttribute("aria-pressed", btn.dataset.brand === b ? "true" : "false");
    });
    document.querySelectorAll(".brand-tag").forEach(function(tag) {
      tag.textContent = b === "hr" ? "HR" : b === "desk" ? "Desk" : "Default";
    });
  }
  function getBrand() {
    try { return localStorage.getItem("porest-brand") || "default"; }
    catch(e) { return "default"; }
  }
  applyBrand(getBrand());
  document.addEventListener("click", function(e) {
    var btn = e.target.closest(".brand-switch button");
    if (!btn) return;
    var b = btn.dataset.brand;
    if (!b) return;
    applyBrand(b);
    try { localStorage.setItem("porest-brand", b); } catch(e) {}
  });

  // Mobile sidebar
  function syncOverlay(open) {
    var ov = document.querySelector(".mobile-overlay");
    if (!ov) return;
    if (open) ov.setAttribute("data-open", "");
    else ov.removeAttribute("data-open");
  }
  document.addEventListener("click", function(e) {
    var t = e.target.closest(".mobile-toggle");
    var ov = e.target.closest(".mobile-overlay");
    var sb = document.querySelector(".sidebar");
    if (!sb) return;
    if (t) {
      var open = sb.getAttribute("data-open") === "true";
      var next = open ? "false" : "true";
      sb.setAttribute("data-open", next);
      syncOverlay(next === "true");
    } else if (ov) {
      sb.setAttribute("data-open", "false");
      syncOverlay(false);
    }
  });

  // Code copy
  document.addEventListener("click", function(e) {
    var btn = e.target.closest(".example-copy");
    if (!btn) return;
    var pre = btn.closest(".example-block").querySelector("pre code");
    if (!pre) return;
    var text = pre.textContent;
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(function() {
        btn.textContent = "Copied!";
        btn.classList.add("copied");
        setTimeout(function() { btn.textContent = "Copy"; btn.classList.remove("copied"); }, 1600);
      });
    }
  });

  // Example Preview / Code 탭 toggle
  document.addEventListener("click", function(e) {
    var tab = e.target.closest(".example-tab");
    if (!tab) return;
    var which = tab.dataset.tab;
    var block = tab.closest(".example-block");
    if (!block) return;
    block.querySelectorAll(".example-tab").forEach(function(t) {
      t.setAttribute("aria-selected", t.dataset.tab === which ? "true" : "false");
    });
    block.querySelectorAll("[data-pane]").forEach(function(p) {
      p.hidden = p.dataset.pane !== which;
    });
  });
})();
`;
}

// ============================================================
// 4. 공통 layout 래퍼
// ============================================================

// NAV는 빌드 시 컴포넌트로부터 동적 구성. buildNav()에서 호출.
let NAV = null;

function buildNav(components) {
  // Components 카테고리별 그룹화
  const byCategory = {};
  for (const c of components) {
    const cat = COMPONENT_CATEGORIES[c.slug];
    if (!cat) continue;
    byCategory[cat.category] = byCategory[cat.category] || [];
    byCategory[cat.category].push({ ...c, sort: cat.sort });
  }
  for (const k of Object.keys(byCategory)) {
    byCategory[k].sort((a, b) => a.sort - b.sort);
  }

  const nav = {
    "Getting Started": [
      { label: "Introduction", href: "/index.html" },
      { label: "Brand identity", href: "/index.html#brand-identity" },
      { label: "Quick start", href: "/index.html#quick-start" },
    ],
    "Tokens": [
      { label: "Colors", href: "/tokens/colors.html" },
      { label: "Typography", href: "/tokens/typography.html" },
      { label: "Spacing", href: "/tokens/spacing.html" },
      { label: "Radius", href: "/tokens/radius.html" },
      { label: "Shadows", href: "/tokens/shadows.html" },
      { label: "Motion", href: "/tokens/motion.html" },
      { label: "Breakpoints", href: "/tokens/breakpoints.html" },
      { label: "Z-index", href: "/tokens/z-index.html" },
    ],
  };

  // Components 카테고리를 sub-section으로
  for (const cat of CATEGORY_ORDER) {
    if (!byCategory[cat]) continue;
    nav[`Components — ${cat}`] = byCategory[cat].map(c => ({
      label: c.name,
      href: `/components/${c.slug}.html`,
    }));
  }

  nav["Examples"] = [{ label: "Coming soon (Phase 3)", soon: true }];

  return nav;
}

function renderSidebar(currentPath) {
  // 디렉토리 깊이 따라 상대 경로 prefix 계산
  const segments = currentPath.split("/").filter(Boolean).slice(0, -1).length;
  const prefix = segments === 0 ? "." : "..".repeat(segments - 1) + "..";

  function abs(href) {
    if (!href) return "#";
    return prefix + href;
  }

  let out = '<aside class="sidebar" aria-label="문서 네비게이션">';
  out += `<div class="brand-row"><strong>Porest</strong><span class="brand-tag">Default</span></div>`;
  // 좁은 viewport에서 topbar의 brand-switch가 숨겨졌을 때 sidebar 안에서 사용 가능
  out += `<div class="brand-switch" role="group" aria-label="브랜드 전환 (사이드바)">
    <button data-brand="default" aria-pressed="true" type="button">Default</button>
    <button data-brand="hr" aria-pressed="false" type="button">HR</button>
    <button data-brand="desk" aria-pressed="false" type="button">Desk</button>
  </div>`;
  for (const [section, items] of Object.entries(NAV)) {
    out += `<div class="nav-section"><div class="nav-eyebrow">${escape(section)}</div><ul class="nav-list">`;
    for (const it of items) {
      const href = it.href ? abs(it.href) : "#";
      const active = it.href && currentPath === it.href ? ' aria-current="page"' : "";
      const cls = it.soon ? "disabled" : "";
      const badge = it.soon ? '<span class="badge-soon">soon</span>' : "";
      out += `<li><a href="${escape(href)}" class="${cls}"${active}>${escape(it.label)}${badge}</a></li>`;
    }
    out += "</ul></div>";
  }
  out += "</aside>";
  return out;
}

function renderTopbar(currentPath, breadcrumb) {
  const segments = currentPath.split("/").filter(Boolean).slice(0, -1).length;
  const prefix = segments === 0 ? "." : "..".repeat(segments - 1) + "..";
  const home = prefix + "/index.html";

  let crumbs = `<a href="${escape(home)}">Porest</a>`;
  for (const c of breadcrumb) {
    crumbs += `<span>/</span>`;
    if (c.href) crumbs += `<a href="${escape(prefix + c.href)}">${escape(c.label)}</a>`;
    else crumbs += `<span>${escape(c.label)}</span>`;
  }

  return `
  <header class="topbar">
    <div class="crumbs">
      <button class="theme-toggle mobile-toggle" type="button" aria-label="메뉴 열기">☰</button>
      ${crumbs}
    </div>
    <div class="controls">
      <div class="brand-switch" role="group" aria-label="브랜드 전환">
        <button data-brand="default" aria-pressed="true" type="button">Default</button>
        <button data-brand="hr" aria-pressed="false" type="button">HR</button>
        <button data-brand="desk" aria-pressed="false" type="button">Desk</button>
      </div>
      <button class="theme-toggle" type="button" aria-label="테마 전환">🌓<span class="theme-toggle-label"> Theme</span></button>
    </div>
  </header>`;
}

// 모든 페이지 공유 — build 시점에 한 번 계산되고 page() 안에서 참조
let TAILWIND_BLOCK = "";

function page({ title, currentPath, breadcrumb, body }) {
  const segments = currentPath.split("/").filter(Boolean).slice(0, -1).length;
  const prefix = segments === 0 ? "." : "..".repeat(segments - 1) + "..";
  return `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escape(title)} — Porest Design</title>
  <link rel="stylesheet" href="${prefix}/assets/tokens.css">
  <link rel="stylesheet" href="${prefix}/assets/site.css">
  <!-- Tailwind v4 browser CDN — @theme 토큰 읽어 utility class 런타임 컴파일 -->
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  <!-- Tailwind 처리 대상 — @theme + brand override + dark mode. 인라인이라 CDN이 정확히 읽음 -->
  <style type="text/tailwindcss">
${TAILWIND_BLOCK}
  </style>
</head>
<body>
  <div class="app">
    ${renderSidebar(currentPath)}
    <div class="main">
      ${renderTopbar(currentPath, breadcrumb)}
      <main class="content">
${body}
      </main>
    </div>
  </div>
  <div class="mobile-overlay" hidden></div>
  <script src="${prefix}/assets/site.js" defer></script>
</body>
</html>
`;
}

// ============================================================
// 5. Landing 페이지
// ============================================================

function pageLanding() {
  const body = `
<section class="hero" id="hero">
  <span class="hero-eyebrow">Porest Design System</span>
  <h1>사람과 일상이<br>숲처럼 자라나는 시스템</h1>
  <p>HR과 Desk, 두 서비스를 위한 단일 디자인 시스템. 한국어 우선, 전 연령 접근성, Toss 톤의 절제와 신뢰감을 레퍼런스로 삼아 토큰부터 컴포넌트까지 일관된 톤을 정의합니다.</p>
  <div class="hero-actions">
    <a class="btn btn--primary" href="./tokens/colors.html">토큰 둘러보기</a>
    <a class="btn btn--outlined" href="https://github.com/lshdainty/porest-design">GitHub</a>
  </div>
</section>

<section id="brand-identity">
  <h2>두 브랜드</h2>
  <p class="lede">같은 baseline, 다른 톤. 한 시스템 안에서 두 서비스의 정체성을 분리합니다.</p>

  <div class="identity-grid">
    <div class="identity-card">
      <span class="identity-swatch" style="background: #357B5F;">HR</span>
      <span class="identity-tag">B2B · 조직 HR</span>
      <h3>Porest HR</h3>
      <p>인사·결재·평가의 절제된 데이터 밀도. 격식체 톤, 데스크탑 중심, forest green primary. 결재 큐의 명확한 위계와 직원 detail의 깊이.</p>
      <code>--color-primary: #357B5F</code>
    </div>
    <div class="identity-card">
      <span class="identity-swatch" style="background: #0147AD;">D</span>
      <span class="identity-tag">B2C · 메모/할일/가계부</span>
      <h3>Porest Desk</h3>
      <p>일상 메모와 할일의 친근한 모바일 톤. 친근체 부분 적용, bottom sheet · pull-to-refresh, cobalt blue primary. 매일의 기록을 단정하게.</p>
      <code>--color-primary: #0147AD</code>
    </div>
    <div class="identity-card">
      <span class="identity-swatch" style="background: #1A1F2E;">P</span>
      <span class="identity-tag">Baseline · 공유</span>
      <h3>Porest Default</h3>
      <p>두 브랜드 공통 토대. neutral 색상·타이포그래피·spacing·radius. brand-agnostic 컴포넌트의 reference. 새로운 brand 추가 시 진입점.</p>
      <code>baseline · 47 colors</code>
    </div>
  </div>
</section>

<section id="quick-start">
  <h2>Quick start</h2>
  <p class="lede">npm 설치 후 verify로 sync · lint · contrast 일괄 검증, build:preview / build:examples로 시각 카탈로그 + 사용 예제 페이지 생성.</p>
  <pre><code>npm install
npm run verify
npm run export:tailwind:all
npm run build:site</code></pre>

  <h3>핵심 가치</h3>
  <ul>
    <li><strong>한국어 우선</strong> — Pretendard 베이스, 본문 15/1.6 한국어 가독성 최적화</li>
    <li><strong>접근성</strong> — WCAG 1.4.3 (4.5:1) / 1.4.11 (3:1) / 2.5.5 (44×44 touch) 자동 검증</li>
    <li><strong>듀얼 브랜드</strong> — neutral baseline 공유 + brand 4 토큰만 fork (primary / primary-light / border-focus / border-focus-light)</li>
    <li><strong>외부 의존성 0</strong> — vanilla Node 도구, design.md spec 직접 파싱, Tailwind v4 native</li>
    <li><strong>다크 모드</strong> — light/dark pair 자동 검증 165 페어 (3 brand)</li>
  </ul>
</section>

<section id="numbers">
  <h2>현재 시스템</h2>
  <div class="spec-grid">
    <div class="spec-card">
      <h4>Tokens</h4>
      <p style="font-size: var(--text-display-md); font-weight: 700; color: var(--color-primary); margin: 0;">180+</p>
      <p style="margin: 4px 0 0; font-size: var(--text-caption); color: var(--color-text-tertiary);">colors · typography · spacing · radius · shadow · motion · breakpoint · touch · z-index · keyframes</p>
    </div>
    <div class="spec-card">
      <h4>Components</h4>
      <p style="font-size: var(--text-display-md); font-weight: 700; color: var(--color-primary); margin: 0;">80+</p>
      <p style="margin: 4px 0 0; font-size: var(--text-caption); color: var(--color-text-tertiary);">shadcn/ui ~100% coverage + Banner/Tag/Popover/File Upload/Treeview 누락 보강</p>
    </div>
    <div class="spec-card">
      <h4>Milestones</h4>
      <p style="font-size: var(--text-display-md); font-weight: 700; color: var(--color-primary); margin: 0;">v82</p>
      <p style="margin: 4px 0 0; font-size: var(--text-caption); color: var(--color-text-tertiary);">v1 → v82 누적 milestone, DESIGN.history/ milestone 백업 1:1</p>
    </div>
  </div>
</section>
`;
  return page({
    title: "Porest Design",
    currentPath: "/index.html",
    breadcrumb: [],
    body,
  });
}

// ============================================================
// 6. Token 페이지들
// ============================================================

function parseColorsBlock(md) {
  // YAML frontmatter colors block 추출
  const lines = md.split("\n");
  let start = -1, end = lines.length;
  for (let i = 0; i < lines.length; i++) {
    if (/^colors:\s*$/.test(lines[i])) { start = i; break; }
  }
  if (start === -1) return [];
  for (let i = start + 1; i < lines.length; i++) {
    if (/^---\s*$/.test(lines[i])) { end = i; break; }
    if (/^[a-z][a-zA-Z0-9_-]*:\s*$/.test(lines[i])) { end = i; break; }
  }
  const colors = [];
  let group = "general";
  for (let i = start + 1; i < end; i++) {
    const line = lines[i];
    const groupMatch = /^\s*#\s*===\s*(.+?)\s*===/.exec(line);
    if (groupMatch) { group = groupMatch[1]; continue; }
    const m = /^\s+([a-z][a-z0-9-]+):\s*"(#[0-9A-Fa-f]{6,8})"/.exec(line);
    if (m) colors.push({ name: m[1], hex: m[2], group });
  }
  return colors;
}

function pageColors() {
  const designMd = readFileSync(resolve(ROOT, "DESIGN.md"), "utf8");
  const colors = parseColorsBlock(designMd);

  // 그룹별 정렬
  const groupOrder = ["page", "surface", "text", "border", "semantic", "chart", "general"];
  const grouped = {};
  for (const c of colors) {
    let key = "general";
    if (c.name.startsWith("bg-")) key = "page";
    else if (c.name.startsWith("surface-")) key = "surface";
    else if (c.name.startsWith("text-")) key = "text";
    else if (c.name.startsWith("border-")) key = "border";
    else if (/^(success|error|warning|info)/.test(c.name)) key = "semantic";
    else if (c.name.startsWith("chart-")) key = "chart";
    grouped[key] = grouped[key] || [];
    grouped[key].push(c);
  }

  const groupTitles = {
    page: "Page background",
    surface: "Surface (default / input)",
    text: "Text (primary / secondary / tertiary / disabled / on-accent)",
    border: "Border (default / strong / focus)",
    semantic: "Semantic (success / error / warning / info)",
    chart: "Chart palette (10 categorical, light / dark variants)",
    general: "Other",
  };

  let groupsHtml = "";
  for (const k of groupOrder) {
    if (!grouped[k]) continue;
    groupsHtml += `<h3>${escape(groupTitles[k])}</h3>`;
    groupsHtml += `<div class="swatch-grid">`;
    for (const c of grouped[k]) {
      const isDark = c.name.endsWith("-dark");
      const isLight = c.name.endsWith("-light");
      const textColor = isDark || /^#[0-7][0-9a-f]{5}$/i.test(c.hex) ? "#fff" : "#000";
      groupsHtml += `<div class="swatch"><div class="swatch-color" style="background: ${c.hex}; color: ${textColor}; display: flex; align-items: center; justify-content: center; font-family: ui-monospace, monospace; font-size: 11px;">${escape(c.hex.toUpperCase())}</div><div class="swatch-meta"><span class="swatch-name">${escape(c.name)}</span></div></div>`;
    }
    groupsHtml += `</div>`;
  }

  const body = `
<h1>Colors</h1>
<p class="lede">Porest는 neutral baseline 47색 + brand 4색(primary / primary-light / border-focus / border-focus-light)으로 구성됩니다. 한국어 본문 4.5:1 대비비, UI 3:1을 모든 색 페어에 자동 검증합니다.</p>

<h2>브랜드 primary</h2>
<p>상단 토글로 Default / HR / Desk 전환하면 primary 색이 바뀌는 걸 확인할 수 있습니다. 4 토큰만 분기, 나머지는 모두 baseline 공유.</p>
<div class="swatch-grid">
  <div class="swatch"><div class="swatch-color" style="background: var(--color-primary); color: var(--color-text-on-accent); display: flex; align-items: center; justify-content: center; font-family: ui-monospace, monospace; font-size: 11px;">primary</div><div class="swatch-meta"><span class="swatch-name">--color-primary</span><span class="swatch-hex">brand-specific</span></div></div>
  <div class="swatch"><div class="swatch-color" style="background: var(--color-primary-light); color: var(--color-text-on-accent); display: flex; align-items: center; justify-content: center; font-family: ui-monospace, monospace; font-size: 11px;">primary-light</div><div class="swatch-meta"><span class="swatch-name">--color-primary-light</span><span class="swatch-hex">dark surface variant</span></div></div>
  <div class="swatch"><div class="swatch-color" style="background: var(--color-border-focus); color: var(--color-text-on-accent); display: flex; align-items: center; justify-content: center; font-family: ui-monospace, monospace; font-size: 11px;">border-focus</div><div class="swatch-meta"><span class="swatch-name">--color-border-focus</span><span class="swatch-hex">2px focus ring</span></div></div>
  <div class="swatch"><div class="swatch-color" style="background: var(--color-border-focus-light); color: var(--color-text-on-accent); display: flex; align-items: center; justify-content: center; font-family: ui-monospace, monospace; font-size: 11px;">border-focus-light</div><div class="swatch-meta"><span class="swatch-name">--color-border-focus-light</span><span class="swatch-hex">dark focus ring</span></div></div>
</div>

<h2>Baseline 47 colors</h2>
${groupsHtml}

<h2>WCAG 검증</h2>
<ul>
  <li><strong>1.4.3 Contrast (Minimum)</strong> — 본문 텍스트 4.5:1 (lint:all로 자동 검증)</li>
  <li><strong>1.4.11 Non-text Contrast</strong> — UI 컴포넌트 / focus indicator 3:1</li>
  <li><strong>1.4.3 Incidental</strong> — disabled / decorative 텍스트 예외 적용</li>
  <li>Dark mode: <code>npm run lint:dark:strict</code>로 165 페어 자동 검증 (3 brand)</li>
</ul>
`;
  return page({
    title: "Colors",
    currentPath: "/tokens/colors.html",
    breadcrumb: [{ label: "Tokens" }, { label: "Colors" }],
    body,
  });
}

function pageTypography() {
  // DESIGN.md typography 블록 파싱
  const md = readFileSync(resolve(ROOT, "DESIGN.md"), "utf8");
  const lines = md.split("\n");
  const types = [];
  let start = -1, end = lines.length;
  for (let i = 0; i < lines.length; i++) {
    if (/^typography:\s*$/.test(lines[i])) { start = i; break; }
  }
  if (start !== -1) {
    for (let i = start + 1; i < lines.length; i++) {
      if (/^---\s*$/.test(lines[i])) { end = i; break; }
      if (/^[a-z][a-zA-Z0-9_-]*:\s*$/.test(lines[i]) && !/^\s/.test(lines[i])) { end = i; break; }
    }
    let current = null;
    for (let i = start + 1; i < end; i++) {
      const line = lines[i];
      const nm = /^\s\s([a-z][a-z0-9-]+):\s*$/.exec(line);
      if (nm) {
        if (current) types.push(current);
        current = { name: nm[1] };
        continue;
      }
      const fm = /^\s\s\s\sfontSize:\s*"?(\d+px)"?/.exec(line);
      if (fm && current) current.fontSize = fm[1];
      const lh = /^\s\s\s\slineHeight:\s*"?([\d.]+)"?/.exec(line);
      if (lh && current) current.lineHeight = lh[1];
      const fw = /^\s\s\s\sfontWeight:\s*(\d+)/.exec(line);
      if (fw && current) current.fontWeight = fw[1];
      const ls = /^\s\s\s\sletterSpacing:\s*"?(-?[\d.]+(?:em|px)?)"?/.exec(line);
      if (ls && current) current.letterSpacing = ls[1];
    }
    if (current) types.push(current);
  }

  let rows = "";
  for (const t of types) {
    rows += `<div class="type-row">
      <div class="meta">
        <strong>${escape(t.name)}</strong>
        ${t.fontSize ? `${escape(t.fontSize)} / ` : ""}${t.lineHeight ? `${escape(t.lineHeight)} / ` : ""}${t.fontWeight ? escape(t.fontWeight) : ""}
        ${t.letterSpacing ? `<br>letter-spacing: ${escape(t.letterSpacing)}` : ""}
      </div>
      <div class="sample" style="font: var(--text-${t.name}--font-weight, 400) var(--text-${t.name}) / var(--text-${t.name}--line-height) var(--font-sans); letter-spacing: var(--text-${t.name}--letter-spacing, 0);">사람과 일상이 숲처럼 자라나는 디자인</div>
    </div>`;
  }

  const body = `
<h1>Typography</h1>
<p class="lede">Pretendard 한국어 우선, Inter 영문 fallback. 본문 15/1.6은 한국어 가독성 최적값 (Toss 베이스). 21종 스케일 — 한국어 + Airbnb 톤(display / title / nav-link / badge / uppercase-tag).</p>

<h2>Font family</h2>
<pre><code>--font-sans: "Pretendard", "Inter", system-ui, sans-serif;</code></pre>

<h2>Scale (${types.length}종)</h2>
${rows}

<h2>가이드</h2>
<ul>
  <li><strong>본문(body)</strong> — 한국어 15/1.6, 영문 16/1.5(body-md). letter-spacing 한국어 0, 영문 -0.01em</li>
  <li><strong>제목 위계</strong> — display-xl (Hero) / heading-xl (페이지 제목) / heading-lg (섹션) / heading-md (카드) / heading-sm (서브)</li>
  <li><strong>UI</strong> — caption-md (label) / caption (helper) / caption-sm (badge·메타) / button-md (버튼) / nav-link (사이드바 / 탭)</li>
  <li><strong>의미 기반</strong> — 크기·무게 직접 지정 금지. 토큰 이름으로만 사용</li>
</ul>
`;
  return page({
    title: "Typography",
    currentPath: "/tokens/typography.html",
    breadcrumb: [{ label: "Tokens" }, { label: "Typography" }],
    body,
  });
}

function pageSpacing() {
  const sizes = [
    { name: "xs", value: "4px" },
    { name: "sm", value: "8px" },
    { name: "md", value: "12px" },
    { name: "lg", value: "16px" },
    { name: "xl", value: "24px" },
    { name: "2xl", value: "32px" },
    { name: "3xl", value: "48px" },
  ];
  let rows = "";
  for (const s of sizes) {
    rows += `<div class="spacing-row">
      <div class="spacing-name">${escape(s.name)}</div>
      <div class="spacing-value">${escape(s.value)}</div>
      <div class="spacing-bar" style="width: ${s.value};"></div>
    </div>`;
  }
  const body = `
<h1>Spacing</h1>
<p class="lede">4px 베이스 7단계. 컴포넌트 padding / margin / gap을 일관되게 분배하기 위한 grid step. v62 Form layout(label↔control 4px / form-group 16px / section 24px) 기반.</p>

${rows}

<h2>사용 패턴</h2>
<ul>
  <li><code>xs</code> (4px) — icon ↔ text, label ↔ control, control ↔ helper</li>
  <li><code>sm</code> (8px) — chip 간격, badge padding, 작은 그룹</li>
  <li><code>md</code> (12px) — 카드 내부 그룹, list row gap</li>
  <li><code>lg</code> (16px) — form-group 간격, 카드 padding default</li>
  <li><code>xl</code> (24px) — section ↔ section, horizontal form label width gap</li>
  <li><code>2xl</code> (32px) — 페이지 본문 padding (데스크탑)</li>
  <li><code>3xl</code> (48px) — Hero 위/아래 여백, 페이지 단락</li>
</ul>
`;
  return page({
    title: "Spacing",
    currentPath: "/tokens/spacing.html",
    breadcrumb: [{ label: "Tokens" }, { label: "Spacing" }],
    body,
  });
}

function pageRadius() {
  const sizes = [
    { name: "xs", value: "2px" },
    { name: "sm", value: "4px" },
    { name: "md", value: "8px" },
    { name: "lg", value: "12px" },
    { name: "xl", value: "16px" },
    { name: "2xl", value: "20px" },
    { name: "full", value: "9999px" },
  ];
  let cards = "";
  for (const r of sizes) {
    cards += `<div class="radius-card">
      <div class="radius-shape" style="border-radius: ${r.value};"></div>
      <div class="spacing-name">${escape(r.name)}</div>
      <div class="spacing-value">${escape(r.value)}</div>
    </div>`;
  }
  const body = `
<h1>Radius</h1>
<p class="lede">spacing(4px 베이스)와 정렬된 7단계. xs(2px)부터 2xl(20px), full(알약·원형). 카드는 lg(12px), 버튼·input은 md(8px), 칩·badge는 sm(4px) 또는 full.</p>

<div class="radius-grid">${cards}</div>

<h2>사용 가이드</h2>
<ul>
  <li><code>xs</code> (2px) — 작은 tag, code highlight, sub-divider</li>
  <li><code>sm</code> (4px) — chip / badge default, 작은 input border</li>
  <li><code>md</code> (8px) — Button default, Input/Textarea default</li>
  <li><code>lg</code> (12px) — Card default, modal medium</li>
  <li><code>xl</code> (16px) — 큰 카드, modal large, sheet</li>
  <li><code>2xl</code> (20px) — Hero card, 강조 surface</li>
  <li><code>full</code> (9999px) — 알약 버튼, 아바타, 원형 icon button, chip pill</li>
</ul>
`;
  return page({
    title: "Radius",
    currentPath: "/tokens/radius.html",
    breadcrumb: [{ label: "Tokens" }, { label: "Radius" }],
    body,
  });
}

function pageShadows() {
  const shadows = [
    { name: "shadow-sm", desc: "subtle (border 대체)", use: "card hover, dropdown 미세 lift" },
    { name: "shadow-md", desc: "noticeable", use: "modal, dropdown panel, popover" },
    { name: "shadow-lg", desc: "prominent", use: "large modal, sheet" },
    { name: "shadow-xl", desc: "dramatic", use: "Hero overlay, floating action" },
  ];
  let cards = "";
  for (const s of shadows) {
    cards += `<div class="shadow-card" style="box-shadow: var(--${s.name});">
      <div style="font-family: ui-monospace, monospace; font-weight: 600;">${escape(s.name)}</div>
      <div style="font-size: var(--text-caption); color: var(--color-text-tertiary); margin-top: 4px;">${escape(s.desc)}</div>
      <div style="font-size: var(--text-caption-sm); color: var(--color-text-secondary); margin-top: 8px;">${escape(s.use)}</div>
    </div>`;
  }
  const body = `
<h1>Shadows</h1>
<p class="lede">4단계 layered shadow (Material 3 / Big Sur 패턴). Tonal Layers(표면 휘도 차)가 1차 elevation 수단, shadow는 2차 보조. dark mode pair는 opacity 2~4배 강화 + inset white top highlight.</p>

<h2>Light surface</h2>
<div class="shadow-grid">${cards}</div>

<h2>토큰</h2>
<table>
<thead><tr><th>Token</th><th>레시피</th><th>주 사용</th></tr></thead>
<tbody>
<tr><td><code>shadow-sm</code></td><td>2-layer 미세 (1px + 4px blur)</td><td>card / dropdown 미세 lift</td></tr>
<tr><td><code>shadow-md</code></td><td>2-layer (4px + 8px blur)</td><td>modal / popover panel</td></tr>
<tr><td><code>shadow-lg</code></td><td>2-layer (12px + 24px blur)</td><td>large modal / sheet</td></tr>
<tr><td><code>shadow-xl</code></td><td>2-layer (24px + 48px blur)</td><td>Hero overlay / floating</td></tr>
</tbody>
</table>

<p>Dark mode 페어: <code>shadow-sm-dark</code> / <code>shadow-md-dark</code> / <code>shadow-lg-dark</code> / <code>shadow-xl-dark</code>. 표면 색이 어둡기 때문에 black opacity 2~4배 강화 + 1px 흰색 inset top highlight (광원 시뮬레이션).</p>

<p>spec(@google/design.md)이 shadow 토큰 타입을 정형화하지 않아 prose-token 패턴 — <code>scripts/build-tailwind-v4.mjs</code>의 <code>parseShadows</code>가 prose 표에서 직접 추출.</p>
`;
  return page({
    title: "Shadows",
    currentPath: "/tokens/shadows.html",
    breadcrumb: [{ label: "Tokens" }, { label: "Shadows" }],
    body,
  });
}

function pageMotion() {
  const durations = [
    { name: "motion-duration-fast", value: "150ms", use: "hover/focus 작은 전환" },
    { name: "motion-duration-base", value: "200ms", use: "drawer / dropdown default" },
    { name: "motion-duration-slow", value: "300ms", use: "modal / page transition" },
    { name: "motion-duration-slower", value: "500ms", use: "Hero / large layout shift" },
    { name: "motion-duration-loop", value: "1500ms", use: "skeleton / spinner / pulse" },
  ];
  const eases = [
    { name: "motion-ease-out", value: "cubic-bezier(0.16, 1, 0.3, 1)", use: "default — Toss · Material 공통" },
    { name: "motion-ease-linear", value: "linear", use: "loop 일정 속도" },
  ];

  let dRows = "";
  for (const d of durations) {
    dRows += `<div class="motion-card">
      <div class="motion-demo" style="animation: site-fade-in ${d.value} var(--motion-ease-out) infinite alternate;"></div>
      <div class="motion-name">${escape(d.name)}</div>
      <div class="motion-value">${escape(d.value)}</div>
      <div style="font-size: var(--text-caption-sm); color: var(--color-text-secondary); text-align: center;">${escape(d.use)}</div>
    </div>`;
  }
  let eRows = "";
  for (const e of eases) {
    eRows += `<div class="motion-card">
      <div class="motion-demo" style="animation: site-spin var(--motion-duration-loop) ${e.value === 'linear' ? 'linear' : `var(--motion-ease-out)`} infinite;"></div>
      <div class="motion-name">${escape(e.name)}</div>
      <div class="motion-value" style="word-break: break-all; text-align: center;">${escape(e.value)}</div>
      <div style="font-size: var(--text-caption-sm); color: var(--color-text-secondary); text-align: center;">${escape(e.use)}</div>
    </div>`;
  }

  const body = `
<h1>Motion</h1>
<p class="lede">5 duration + 2 easing + 14 keyframes. v32 단발 전환(hover/modal entrance) + v63 반복(skeleton/spinner) + v74 keyframe library(fade/slide/scale/bounce/shake/spin/pulse/shimmer/ping). brand-neutral.</p>

<h2>Duration (5종)</h2>
<div class="spec-grid">${dRows}</div>

<h2>Easing (2종)</h2>
<div class="spec-grid">${eRows}</div>

<h2>Keyframes (14종, v74)</h2>
<p>모두 baseline 정의(brand-neutral). <code>exports/tokens.css</code>에 자동 포함.</p>
<table>
<thead><tr><th>이름</th><th>구분</th><th>주 사용</th></tr></thead>
<tbody>
<tr><td><code>fade-in</code> / <code>fade-out</code></td><td>단발</td><td>dropdown / popover 등장 / 사라짐</td></tr>
<tr><td><code>slide-in-{up,down,left,right}</code></td><td>단발</td><td>drawer / sheet / toast 방향별 등장</td></tr>
<tr><td><code>scale-in</code> / <code>scale-out</code></td><td>단발</td><td>modal / dialog (scale 0.96 → 1)</td></tr>
<tr><td><code>bounce-in</code></td><td>단발</td><td>celebration · success indicator (over-shoot)</td></tr>
<tr><td><code>shake</code></td><td>단발</td><td>form validation error 강조</td></tr>
<tr><td><code>spin</code></td><td>loop</td><td>spinner · refresh icon</td></tr>
<tr><td><code>pulse</code></td><td>loop</td><td>dot indicator · attention</td></tr>
<tr><td><code>shimmer</code></td><td>loop</td><td>skeleton (linear-gradient translateX)</td></tr>
<tr><td><code>ping</code></td><td>loop</td><td>notification dot · alert</td></tr>
</tbody>
</table>

<h2>WCAG · prefers-reduced-motion</h2>
<pre><code>@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}</code></pre>
<p>2.3.3 Animation from Interactions: 200ms 초과 단발 + 모든 loop는 reduce 시 비활성. 컴포넌트 spec에서 일괄 적용.</p>
`;
  return page({
    title: "Motion",
    currentPath: "/tokens/motion.html",
    breadcrumb: [{ label: "Tokens" }, { label: "Motion" }],
    body,
  });
}

function pageBreakpoints() {
  const bps = [
    { name: "breakpoint-sm", value: "640px", note: "모바일 ↔ 큰 모바일 / 작은 태블릿 (Tailwind sm = 640)" },
    { name: "breakpoint-md", value: "736px", note: "태블릿 portrait — Apple Store reference. Tailwind md(768)와 다름" },
    { name: "breakpoint-lg", value: "834px", note: "태블릿 landscape (Apple iPad)" },
    { name: "breakpoint-xl", value: "1069px", note: "데스크탑 medium (Apple Store 메인 grid)" },
    { name: "breakpoint-2xl", value: "1441px", note: "데스크탑 large — Hero 8-column max grid" },
  ];
  let rows = "";
  for (const b of bps) {
    rows += `<div class="bp-row">
      <div class="bp-name">${escape(b.name)}</div>
      <div class="bp-value">${escape(b.value)}</div>
      <div class="bp-note">${escape(b.note)}</div>
    </div>`;
  }
  const body = `
<h1>Breakpoints</h1>
<p class="lede">5단계 viewport 분기. Apple Store 톤(640 / 736 / 834 / 1069 / 1441) — Tailwind v4 기본과 일부 다름. <code>--breakpoint-*</code> namespace는 Tailwind v4 표준.</p>

<h2>토큰</h2>
${rows}

<h2>적용 패턴</h2>
<ul>
  <li><strong>모바일 우선</strong> (Desk B2C) — base는 모바일, <code>@media (min-width: var(--breakpoint-md))</code>로 데스크탑 분기</li>
  <li><strong>데스크탑 우선</strong> (HR B2B) — base 데스크탑, <code>@media (max-width: var(--breakpoint-md))</code>로 모바일 적응</li>
  <li>Form layout: stacked → horizontal 전환 = <code>breakpoint-md</code> 기준</li>
  <li>Hero typography: 4단계 scale (display-xl ↔ heading-md) 분기</li>
</ul>
`;
  return page({
    title: "Breakpoints",
    currentPath: "/tokens/breakpoints.html",
    breadcrumb: [{ label: "Tokens" }, { label: "Breakpoints" }],
    body,
  });
}

function pageZIndex() {
  const layers = [
    { name: "z-base", value: 0, label: "default 평면" },
    { name: "z-dropdown", value: 1000, label: "dropdown / select panel / autocomplete / tooltip" },
    { name: "z-sticky", value: 1100, label: "sticky header / sticky reservation rail / CTA" },
    { name: "z-drawer", value: 1200, label: "drawer / side panel / bottom sheet" },
    { name: "z-modal", value: 1300, label: "modal dialog + overlay-dim" },
    { name: "z-toast", value: 1400, label: "toast / snackbar (모든 layer 위)" },
  ];
  let rows = "";
  for (let i = 0; i < layers.length; i++) {
    const l = layers[i];
    rows += `<div class="bp-row" style="--row-i: ${i};">
      <div class="bp-name">${escape(l.name)}</div>
      <div class="bp-value">${l.value}</div>
      <div class="bp-note">${escape(l.label)}</div>
    </div>`;
  }

  let stackCards = "";
  layers.slice().reverse().forEach((l, i) => {
    const top = 16 + i * 32;
    const left = 16 + i * 32;
    stackCards += `<div class="zindex-card" style="top: ${top}px; left: ${left}px; z-index: ${l.value};">${escape(l.name)} — ${l.value}</div>`;
  });

  const body = `
<h1>Z-index</h1>
<p class="lede">6단계 layering. 100 단위 간격 — 중간 layer 삽입 여유. v43 Modal / v45 Dropdown / v46 Toast 등 spec의 prose 표현(최상단/위)을 정형 numeric 토큰화.</p>

<h2>Layer stack</h2>
<div class="zindex-stack">${stackCards}</div>

<h2>토큰</h2>
${rows}

<h2>충돌 우선순위</h2>
<pre><code>z-toast (1400) &gt; z-modal (1300) &gt; z-drawer (1200) &gt; z-sticky (1100) &gt; z-dropdown (1000) &gt; z-base (0)</code></pre>

<p>직관: 사용자 알림(toast)은 모달 위, 모달은 drawer 위, drawer는 sticky 위. dropdown은 페이지 콘텐츠 위지만 다른 layered 컴포넌트보단 아래.</p>

<p>중간 layer 필요 시: dropdown 내부 nested submenu(<code>1010</code>), modal 내부 dropdown(<code>1310</code>) 등 100 단위 사이 활용. 별도 토큰 정의는 사용 사례 등장 후.</p>

<p>Component island 격리: 부모에 <code>isolation: isolate</code> 권장 — z-index scope를 island로 격리해 다른 island와 우선순위 충돌 회피.</p>
`;
  return page({
    title: "Z-index",
    currentPath: "/tokens/z-index.html",
    breadcrumb: [{ label: "Tokens" }, { label: "Z-index" }],
    body,
  });
}

// ============================================================
// 7. EXAMPLES.md 파서 + 컴포넌트 페이지
// ============================================================

function slugify(s) {
  return s.toLowerCase()
    .replace(/[\/&]/g, "-")
    .replace(/[^a-z0-9가-힣\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

// EXAMPLES.md → 섹션 배열. 각 섹션 = { name, slug, paragraphs, examples: [{ lang, code }] }
function parseExamplesMd() {
  const md = readFileSync(resolve(ROOT, "EXAMPLES.md"), "utf8");
  const lines = md.split("\n");
  const sections = [];
  let current = null;
  let inCode = false;
  let codeBuf = [];
  let codeLang = "";
  let proseBuf = [];

  function flushProse() {
    if (current && proseBuf.length > 0) {
      const text = proseBuf.join("\n").trim();
      if (text) {
        // 코드 직후 prose는 example label로, 그 외는 paragraph로
        if (current.examples.length > 0 && !current.examples[current.examples.length - 1].label && proseBuf.length <= 3) {
          current.examples[current.examples.length - 1].label = text;
        } else {
          current.paragraphs.push(text);
        }
      }
      proseBuf = [];
    }
  }

  for (const line of lines) {
    // h2 = section
    const h = /^##\s+(.+)$/.exec(line);
    if (h && !inCode) {
      flushProse();
      const name = h[1].trim();
      // Skip 목차 / 다음 참조 / 토큰 alias 안내 등 meta 섹션
      if (/^(목차|다음 참조|토큰 alias 안내)/.test(name)) {
        current = null;
        continue;
      }
      current = { name, slug: slugify(name), paragraphs: [], examples: [] };
      sections.push(current);
      continue;
    }
    if (line.startsWith("```")) {
      if (!inCode) {
        flushProse();
        inCode = true;
        codeLang = line.slice(3).trim() || "html";
        codeBuf = [];
      } else {
        if (current) {
          current.examples.push({ lang: codeLang, code: codeBuf.join("\n"), label: null });
        }
        inCode = false;
      }
      continue;
    }
    if (inCode) {
      codeBuf.push(line);
      continue;
    }
    if (line.startsWith("---") && line.replace(/-/g, "").trim() === "") continue;
    if (current) proseBuf.push(line);
  }
  flushProse();
  return sections;
}

// 카테고리 매핑 (slug → { category, sortKey })
const COMPONENT_CATEGORIES = {
  "button": { category: "Forms", sort: 1 },
  "input-textarea": { category: "Forms", sort: 2 },
  "select-combobox": { category: "Forms", sort: 3 },
  "checkbox-radio-switch": { category: "Forms", sort: 4 },
  "form-layout-validation": { category: "Forms", sort: 5 },
  "file-upload": { category: "Forms", sort: 6 },

  "card": { category: "Layout", sort: 1 },
  "avatar": { category: "Layout", sort: 2 },

  "badge-tag-chip": { category: "Data Display", sort: 1 },
  "calendar-date-range-picker": { category: "Data Display", sort: 2 },

  "banner": { category: "Feedback", sort: 1 },
  "toast-sonner": { category: "Feedback", sort: 2 },
  "skeleton-spinner-progress": { category: "Feedback", sort: 3 },
  "empty-state": { category: "Feedback", sort: 4 },

  "modal-dialog": { category: "Overlay", sort: 1 },
  "drawer-sheet": { category: "Overlay", sort: 2 },
  "tooltip-popover-hover-card": { category: "Overlay", sort: 3 },
  "dropdown-context-menu": { category: "Overlay", sort: 4 },

  "tabs": { category: "Navigation", sort: 1 },
  "breadcrumb-sidebar": { category: "Navigation", sort: 2 },
  "pagination-stepper": { category: "Navigation", sort: 3 },

  "accordion-collapsible": { category: "Disclosure", sort: 1 },
  "treeview": { category: "Disclosure", sort: 2 },

  "animation-patterns": { category: "Reference", sort: 1 },
};

const CATEGORY_ORDER = ["Forms", "Layout", "Navigation", "Data Display", "Feedback", "Overlay", "Disclosure", "Reference"];

// 컴포넌트 slug → preview.html render 함수 매핑
// 각 함수는 brand 객체 받아 <section> HTML 반환 (custom CSS 사용 — pageCss로 스타일링)
function getDemoFunctions(slug) {
  switch (slug) {
    case "button": return [renderButtonGallery];
    case "card": return [renderListingDetail];
    case "input-textarea": return [renderForm];
    case "form-layout-validation": return [renderForm, renderBatchV73V78];
    case "select-combobox": return [renderShadcnInput];
    case "checkbox-radio-switch": return [renderShadcnInput];
    case "modal-dialog": return [renderModal];
    case "drawer-sheet": return [renderBatchV67];
    case "toast-sonner": return [renderToasts, renderShadcnExtras];
    case "skeleton-spinner-progress": return [renderSkeleton, renderBatchV67];
    case "empty-state": return [renderEmptyState];
    case "calendar-date-range-picker": return [renderCalendar, renderShadcnExtras];
    case "tabs": return [renderListingDetail];
    case "breadcrumb-sidebar": return [renderShadcnNav];
    case "pagination-stepper": return [renderBatchV67];
    case "accordion-collapsible": return [renderShadcnDisclose];
    case "tooltip-popover-hover-card": return [renderShadcnDisclose, renderBatchV73V78];
    case "dropdown-context-menu": return [renderShadcnDisclose];
    case "treeview": return [renderBatchV73V78];
    case "file-upload": return [renderBatchV73V78];
    case "banner": return [renderBatchV73V78];
    case "badge-tag-chip": return [renderBatchV73V78];
    case "avatar": return [renderListingDetail];
    case "animation-patterns": return [renderBatchV73V78];
    default: return [];
  }
}

function pageComponent(component, brand) {
  const cat = COMPONENT_CATEGORIES[component.slug] || { category: "Other" };

  function inlineMarkdown(s) {
    return escape(s).replace(/`([^`]+)`/g, (_, c) => `<code>${c}</code>`);
  }

  // 첫 paragraph는 lede로
  const lede = component.paragraphs[0] || "";
  const restParas = component.paragraphs.slice(1);

  let body = `
<h1>${escape(component.name)}</h1>
${lede ? `<p class="lede">${inlineMarkdown(lede)}</p>` : ""}

<div class="component-meta">
  <a class="tag">${escape(cat.category)}</a>
  <a href="https://github.com/lshdainty/porest-design/blob/main/EXAMPLES.md#${escape(component.slug)}" target="_blank" rel="noopener">EXAMPLES.md ↗</a>
  <a href="https://github.com/lshdainty/porest-design/blob/main/DESIGN.md" target="_blank" rel="noopener">DESIGN.md spec ↗</a>
</div>
`;

  // === Live demo (preview.html의 render 함수 직접 호출) ===
  const demoFns = getDemoFunctions(component.slug);
  if (demoFns.length > 0) {
    body += `<h2>데모</h2>\n`;
    body += `<p class="lede" style="font-size: var(--text-caption-md); margin-bottom: 16px;">preview.html의 컴포넌트 데모를 그대로 임베드. 상단 Default / HR / Desk 토글로 색상 분기 확인 가능.</p>\n`;
    body += `<div class="demo-frame">\n`;
    for (const fn of demoFns) {
      body += fn(brand) + "\n";
    }
    body += `</div>\n`;
  }

  // === EXAMPLES.md 코드 (참고용 — Tailwind utility 형태) ===
  if (component.examples.length > 0) {
    body += `<h2>코드 예제 (Tailwind v4)</h2>\n`;
    body += `<p class="lede" style="font-size: var(--text-caption-md); margin-bottom: 16px;">EXAMPLES.md의 Tailwind utility 코드. copy-paste 후 자기 프로젝트에 활용.</p>\n`;
    for (let i = 0; i < component.examples.length; i++) {
      const ex = component.examples[i];
      body += `<div class="example-block" data-example>
  <div class="example-head">
    <div class="example-tabs">
      <button class="example-tab" data-tab="preview" aria-selected="true" type="button">Preview</button>
      <button class="example-tab" data-tab="code" aria-selected="false" type="button">Code</button>
    </div>
    <button class="example-copy" type="button">Copy</button>
  </div>
  <div class="example-preview" data-pane="preview">
    <div class="preview-frame">${ex.code}</div>
  </div>
  <div class="example-code" data-pane="code" hidden>
    <pre><code class="lang-${escape(ex.lang)}">${escape(ex.code)}</code></pre>
  </div>
  ${ex.label ? `<div class="example-label">${escape(ex.label)}</div>` : ""}
</div>
`;
    }
  }

  if (restParas.length > 0) {
    body += `<h2>가이드</h2>\n`;
    for (const p of restParas) {
      body += `<p>${inlineMarkdown(p)}</p>\n`;
    }
  }

  body += `
<div class="callout">
  <div>
    <strong>관련 문서</strong> · 사양은 <a href="https://github.com/lshdainty/porest-design/blob/main/DESIGN.md" target="_blank" rel="noopener">DESIGN.md</a> spec 참조 · HR/Desk 분기 톤은 <a href="https://github.com/lshdainty/porest-design/blob/main/DESIGN.hr.md" target="_blank" rel="noopener">DESIGN.hr.md</a> / <a href="https://github.com/lshdainty/porest-design/blob/main/DESIGN.desk.md" target="_blank" rel="noopener">DESIGN.desk.md</a>.
  </div>
</div>
`;

  return page({
    title: component.name,
    currentPath: `/components/${component.slug}.html`,
    breadcrumb: [
      { label: "Components" },
      { label: cat.category },
      { label: component.name },
    ],
    body,
  });
}

// ============================================================
// 8. Build
// ============================================================

function ensureDir(p) { mkdirSync(p, { recursive: true }); }

ensureDir(OUT);
ensureDir(resolve(OUT, "tokens"));
ensureDir(resolve(OUT, "components"));
ensureDir(resolve(OUT, "assets"));

// EXAMPLES.md 파싱 → NAV 구성
const components = parseExamplesMd().filter(c => COMPONENT_CATEGORIES[c.slug]);
NAV = buildNav(components);

const tokens = buildTokens();
TAILWIND_BLOCK = tokens.tailwindBlock;
writeFileSync(resolve(OUT, "assets/tokens.css"), tokens.rootCss);
// site.css = 사이트 layout + preview.html demo CSS (preview의 sc-card / btn-* / son-toast 등)
// 단, preview의 site-level 셀렉터(body, .theme-toggle, .app 등)는 제거 — site CSS와 충돌
function sanitizePreviewCss(css) {
  // 충돌 셀렉터 패턴 — selectorPart trim + comment 제거 후 매칭
  // 셀렉터 끝(또는 다음 문자가 word-extension이 아닌)을 검사 — 더 길게 이어진 이름과 구분
  const conflictPatterns = [
    /^body(?![-a-zA-Z0-9_])/,
    /^\.theme-toggle(?![-a-zA-Z0-9_])/,
    /^\.theme-toggle-icon(?![-a-zA-Z0-9_])/,
    /^\.theme-toggle-(?:dark|light)-(?:text|icon)(?![-a-zA-Z0-9_])/,
    /^\[data-theme="(?:light|dark)"\]\s+body(?![-a-zA-Z0-9_])/,
    /^\[data-theme="(?:light|dark)"\]\s+\.theme-toggle(?![-a-zA-Z0-9_])/,
    /^main(?![-a-zA-Z0-9_])/,
    /^html(?![-a-zA-Z0-9_])/,
  ];
  function cleanSelector(s) {
    // 리딩 whitespace + CSS 주석 제거
    return s.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s+/, "").replace(/\s+$/, "");
  }
  // CSS rule 블록 단위로 split + filter (간단한 brace 기반 파서)
  const out = [];
  let i = 0;
  while (i < css.length) {
    // selector 부분 (block 시작 전까지)
    let j = i;
    let depth = 0;
    while (j < css.length) {
      if (css[j] === "{") { depth = 1; break; }
      j++;
    }
    if (depth === 0) { out.push(css.slice(i)); break; }
    // selector 추출
    const selectorPart = css.slice(i, j);
    // body 매칭 (rule 단위) — block 끝까지 찾기
    let k = j + 1;
    let braceDepth = 1;
    while (k < css.length && braceDepth > 0) {
      if (css[k] === "{") braceDepth++;
      else if (css[k] === "}") braceDepth--;
      k++;
    }
    const ruleBlock = css.slice(i, k);
    const cleanedSelector = cleanSelector(selectorPart);
    // @media / @keyframes 등 at-rule은 그대로 통과 (내부 rule도 함께)
    if (cleanedSelector.startsWith("@")) {
      out.push(ruleBlock);
    } else {
      // 충돌 selector 검사 (cleaned 기준)
      const conflicts = conflictPatterns.some(re => re.test(cleanedSelector));
      if (!conflicts) out.push(ruleBlock);
      else out.push(`/* SKIPPED conflicting: ${cleanedSelector.slice(0, 60)}... */\n`);
    }
    i = k;
  }
  return out.join("");
}
const combinedSiteCss = siteCss() + "\n\n/* === preview.html demo CSS (sanitized) === */\n" + sanitizePreviewCss(previewPageCss());
writeFileSync(resolve(OUT, "assets/site.css"), combinedSiteCss);
writeFileSync(resolve(OUT, "assets/site.js"), siteJs());

// brand 객체 — preview.html demo 함수에 전달. brand.key === "default" / "hr" / "desk".
// 사이트는 한 번에 한 brand만 빌드 안 함 — Default brand로 정적 렌더, JS toggle로 색상 전환.
const tokensCss = readFileSync(resolve(ROOT, "exports/tokens.css"), "utf8");
const parsedTokens = parseTokensFromCss(tokensCss);
const brand = brandProfile("Default", parsedTokens);

writeFileSync(resolve(OUT, "index.html"), pageLanding());
writeFileSync(resolve(OUT, "tokens/colors.html"), pageColors());
writeFileSync(resolve(OUT, "tokens/typography.html"), pageTypography());
writeFileSync(resolve(OUT, "tokens/spacing.html"), pageSpacing());
writeFileSync(resolve(OUT, "tokens/radius.html"), pageRadius());
writeFileSync(resolve(OUT, "tokens/shadows.html"), pageShadows());
writeFileSync(resolve(OUT, "tokens/motion.html"), pageMotion());
writeFileSync(resolve(OUT, "tokens/breakpoints.html"), pageBreakpoints());
writeFileSync(resolve(OUT, "tokens/z-index.html"), pageZIndex());

for (const c of components) {
  writeFileSync(resolve(OUT, `components/${c.slug}.html`), pageComponent(c, brand));
}

console.log("✓ exports/site/");
console.log("  index.html");
console.log("  tokens/{colors,typography,spacing,radius,shadows,motion,breakpoints,z-index}.html (8 페이지)");
console.log(`  components/*.html (${components.length} 페이지 — preview.html 데모 임베드 + Tailwind 코드 참고)`);
console.log("  assets/{tokens,site}.css + site.js");
